// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2s/Club_Proxy.proto

package protobuf.clazz.s2s;

public final class ClubProxyProto {
  private ClubProxyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 accountId = 1;
    /**
     * <code>required int64 accountId = 1;</code>
     *
     * <pre>
     *玩家id
     * </pre>
     */
    boolean hasAccountId();
    /**
     * <code>required int64 accountId = 1;</code>
     *
     * <pre>
     *玩家id
     * </pre>
     */
    long getAccountId();

    // required int32 status = 2;
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *玩家状态。1观战，2参战
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *玩家状态。1观战，2参战
     * </pre>
     */
    int getStatus();

    // optional int32 roomId = 3;
    /**
     * <code>optional int32 roomId = 3;</code>
     *
     * <pre>
     *房间id
     * </pre>
     */
    boolean hasRoomId();
    /**
     * <code>optional int32 roomId = 3;</code>
     *
     * <pre>
     *房间id
     * </pre>
     */
    int getRoomId();
  }
  /**
   * Protobuf type {@code s2s.PlayerStatus}
   *
   * <pre>
   *logic-&gt;proxy,玩家已经成为观察子
   * </pre>
   */
  public static final class PlayerStatus extends
      com.google.protobuf.GeneratedMessage
      implements PlayerStatusOrBuilder {
    // Use PlayerStatus.newBuilder() to construct.
    private PlayerStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerStatus defaultInstance;
    public static PlayerStatus getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              status_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              roomId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_PlayerStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_PlayerStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.class, protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerStatus> PARSER =
        new com.google.protobuf.AbstractParser<PlayerStatus>() {
      public PlayerStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 accountId = 1;
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>required int64 accountId = 1;</code>
     *
     * <pre>
     *玩家id
     * </pre>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 accountId = 1;</code>
     *
     * <pre>
     *玩家id
     * </pre>
     */
    public long getAccountId() {
      return accountId_;
    }

    // required int32 status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *玩家状态。1观战，2参战
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 status = 2;</code>
     *
     * <pre>
     *玩家状态。1观战，2参战
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    // optional int32 roomId = 3;
    public static final int ROOMID_FIELD_NUMBER = 3;
    private int roomId_;
    /**
     * <code>optional int32 roomId = 3;</code>
     *
     * <pre>
     *房间id
     * </pre>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 roomId = 3;</code>
     *
     * <pre>
     *房间id
     * </pre>
     */
    public int getRoomId() {
      return roomId_;
    }

    private void initFields() {
      accountId_ = 0L;
      status_ = 0;
      roomId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, roomId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, roomId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.s2s.ClubProxyProto.PlayerStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code s2s.PlayerStatus}
     *
     * <pre>
     *logic-&gt;proxy,玩家已经成为观察子
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_PlayerStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_PlayerStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.class, protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder.class);
      }

      // Construct using protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_PlayerStatus_descriptor;
      }

      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus getDefaultInstanceForType() {
        return protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance();
      }

      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus build() {
        protobuf.clazz.s2s.ClubProxyProto.PlayerStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus buildPartial() {
        protobuf.clazz.s2s.ClubProxyProto.PlayerStatus result = new protobuf.clazz.s2s.ClubProxyProto.PlayerStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.roomId_ = roomId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.s2s.ClubProxyProto.PlayerStatus) {
          return mergeFrom((protobuf.clazz.s2s.ClubProxyProto.PlayerStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.s2s.ClubProxyProto.PlayerStatus other) {
        if (other == protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        if (!hasStatus()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.s2s.ClubProxyProto.PlayerStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.s2s.ClubProxyProto.PlayerStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 accountId = 1;
      private long accountId_ ;
      /**
       * <code>required int64 accountId = 1;</code>
       *
       * <pre>
       *玩家id
       * </pre>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 accountId = 1;</code>
       *
       * <pre>
       *玩家id
       * </pre>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       *
       * <pre>
       *玩家id
       * </pre>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       *
       * <pre>
       *玩家id
       * </pre>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      // required int32 status = 2;
      private int status_ ;
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *玩家状态。1观战，2参战
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *玩家状态。1观战，2参战
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *玩家状态。1观战，2参战
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 2;</code>
       *
       * <pre>
       *玩家状态。1观战，2参战
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }

      // optional int32 roomId = 3;
      private int roomId_ ;
      /**
       * <code>optional int32 roomId = 3;</code>
       *
       * <pre>
       *房间id
       * </pre>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 roomId = 3;</code>
       *
       * <pre>
       *房间id
       * </pre>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>optional int32 roomId = 3;</code>
       *
       * <pre>
       *房间id
       * </pre>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000004;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 roomId = 3;</code>
       *
       * <pre>
       *房间id
       * </pre>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:s2s.PlayerStatus)
    }

    static {
      defaultInstance = new PlayerStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:s2s.PlayerStatus)
  }

  public interface S2SReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cmd = 1;
    /**
     * <code>required int32 cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required int32 cmd = 1;</code>
     */
    int getCmd();

    // optional .s2s.PlayerStatus status = 2;
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    boolean hasStatus();
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    protobuf.clazz.s2s.ClubProxyProto.PlayerStatus getStatus();
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder getStatusOrBuilder();
  }
  /**
   * Protobuf type {@code s2s.S2SReq}
   */
  public static final class S2SReq extends
      com.google.protobuf.GeneratedMessage
      implements S2SReqOrBuilder {
    // Use S2SReq.newBuilder() to construct.
    private S2SReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private S2SReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final S2SReq defaultInstance;
    public static S2SReq getDefaultInstance() {
      return defaultInstance;
    }

    public S2SReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private S2SReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = status_.toBuilder();
              }
              status_ = input.readMessage(protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(status_);
                status_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_S2SReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_S2SReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.s2s.ClubProxyProto.S2SReq.class, protobuf.clazz.s2s.ClubProxyProto.S2SReq.Builder.class);
    }

    public static com.google.protobuf.Parser<S2SReq> PARSER =
        new com.google.protobuf.AbstractParser<S2SReq>() {
      public S2SReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2SReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<S2SReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>required int32 cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // optional .s2s.PlayerStatus status = 2;
    public static final int STATUS_FIELD_NUMBER = 2;
    private protobuf.clazz.s2s.ClubProxyProto.PlayerStatus status_;
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus getStatus() {
      return status_;
    }
    /**
     * <code>optional .s2s.PlayerStatus status = 2;</code>
     */
    public protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder getStatusOrBuilder() {
      return status_;
    }

    private void initFields() {
      cmd_ = 0;
      status_ = protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasStatus()) {
        if (!getStatus().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, status_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.S2SReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.s2s.ClubProxyProto.S2SReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code s2s.S2SReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.s2s.ClubProxyProto.S2SReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_S2SReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_S2SReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.s2s.ClubProxyProto.S2SReq.class, protobuf.clazz.s2s.ClubProxyProto.S2SReq.Builder.class);
      }

      // Construct using protobuf.clazz.s2s.ClubProxyProto.S2SReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (statusBuilder_ == null) {
          status_ = protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_S2SReq_descriptor;
      }

      public protobuf.clazz.s2s.ClubProxyProto.S2SReq getDefaultInstanceForType() {
        return protobuf.clazz.s2s.ClubProxyProto.S2SReq.getDefaultInstance();
      }

      public protobuf.clazz.s2s.ClubProxyProto.S2SReq build() {
        protobuf.clazz.s2s.ClubProxyProto.S2SReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.s2s.ClubProxyProto.S2SReq buildPartial() {
        protobuf.clazz.s2s.ClubProxyProto.S2SReq result = new protobuf.clazz.s2s.ClubProxyProto.S2SReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (statusBuilder_ == null) {
          result.status_ = status_;
        } else {
          result.status_ = statusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.s2s.ClubProxyProto.S2SReq) {
          return mergeFrom((protobuf.clazz.s2s.ClubProxyProto.S2SReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.s2s.ClubProxyProto.S2SReq other) {
        if (other == protobuf.clazz.s2s.ClubProxyProto.S2SReq.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasStatus()) {
          mergeStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        if (hasStatus()) {
          if (!getStatus().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.s2s.ClubProxyProto.S2SReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.s2s.ClubProxyProto.S2SReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cmd = 1;
      private int cmd_ ;
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }

      // optional .s2s.PlayerStatus status = 2;
      private protobuf.clazz.s2s.ClubProxyProto.PlayerStatus status_ = protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.clazz.s2s.ClubProxyProto.PlayerStatus, protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder, protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder> statusBuilder_;
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus getStatus() {
        if (statusBuilder_ == null) {
          return status_;
        } else {
          return statusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public Builder setStatus(protobuf.clazz.s2s.ClubProxyProto.PlayerStatus value) {
        if (statusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          status_ = value;
          onChanged();
        } else {
          statusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public Builder setStatus(
          protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder builderForValue) {
        if (statusBuilder_ == null) {
          status_ = builderForValue.build();
          onChanged();
        } else {
          statusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public Builder mergeStatus(protobuf.clazz.s2s.ClubProxyProto.PlayerStatus value) {
        if (statusBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              status_ != protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance()) {
            status_ =
              protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.newBuilder(status_).mergeFrom(value).buildPartial();
          } else {
            status_ = value;
          }
          onChanged();
        } else {
          statusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public Builder clearStatus() {
        if (statusBuilder_ == null) {
          status_ = protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.getDefaultInstance();
          onChanged();
        } else {
          statusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder getStatusBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      public protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder getStatusOrBuilder() {
        if (statusBuilder_ != null) {
          return statusBuilder_.getMessageOrBuilder();
        } else {
          return status_;
        }
      }
      /**
       * <code>optional .s2s.PlayerStatus status = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.clazz.s2s.ClubProxyProto.PlayerStatus, protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder, protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder> 
          getStatusFieldBuilder() {
        if (statusBuilder_ == null) {
          statusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.clazz.s2s.ClubProxyProto.PlayerStatus, protobuf.clazz.s2s.ClubProxyProto.PlayerStatus.Builder, protobuf.clazz.s2s.ClubProxyProto.PlayerStatusOrBuilder>(
                  status_,
                  getParentForChildren(),
                  isClean());
          status_ = null;
        }
        return statusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:s2s.S2SReq)
    }

    static {
      defaultInstance = new S2SReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:s2s.S2SReq)
  }

  public interface GoldRoomMsgReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 accountId = 1;
    /**
     * <code>required int64 accountId = 1;</code>
     */
    boolean hasAccountId();
    /**
     * <code>required int64 accountId = 1;</code>
     */
    long getAccountId();

    // optional int32 logicIndex = 2;
    /**
     * <code>optional int32 logicIndex = 2;</code>
     */
    boolean hasLogicIndex();
    /**
     * <code>optional int32 logicIndex = 2;</code>
     */
    int getLogicIndex();
  }
  /**
   * Protobuf type {@code s2s.GoldRoomMsgReq}
   */
  public static final class GoldRoomMsgReq extends
      com.google.protobuf.GeneratedMessage
      implements GoldRoomMsgReqOrBuilder {
    // Use GoldRoomMsgReq.newBuilder() to construct.
    private GoldRoomMsgReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GoldRoomMsgReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GoldRoomMsgReq defaultInstance;
    public static GoldRoomMsgReq getDefaultInstance() {
      return defaultInstance;
    }

    public GoldRoomMsgReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GoldRoomMsgReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              logicIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_GoldRoomMsgReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_GoldRoomMsgReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.class, protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.Builder.class);
    }

    public static com.google.protobuf.Parser<GoldRoomMsgReq> PARSER =
        new com.google.protobuf.AbstractParser<GoldRoomMsgReq>() {
      public GoldRoomMsgReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GoldRoomMsgReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GoldRoomMsgReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 accountId = 1;
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>required int64 accountId = 1;</code>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 accountId = 1;</code>
     */
    public long getAccountId() {
      return accountId_;
    }

    // optional int32 logicIndex = 2;
    public static final int LOGICINDEX_FIELD_NUMBER = 2;
    private int logicIndex_;
    /**
     * <code>optional int32 logicIndex = 2;</code>
     */
    public boolean hasLogicIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 logicIndex = 2;</code>
     */
    public int getLogicIndex() {
      return logicIndex_;
    }

    private void initFields() {
      accountId_ = 0L;
      logicIndex_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAccountId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, logicIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, logicIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code s2s.GoldRoomMsgReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_GoldRoomMsgReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_GoldRoomMsgReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.class, protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.Builder.class);
      }

      // Construct using protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        logicIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.s2s.ClubProxyProto.internal_static_s2s_GoldRoomMsgReq_descriptor;
      }

      public protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq getDefaultInstanceForType() {
        return protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.getDefaultInstance();
      }

      public protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq build() {
        protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq buildPartial() {
        protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq result = new protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.logicIndex_ = logicIndex_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq) {
          return mergeFrom((protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq other) {
        if (other == protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        if (other.hasLogicIndex()) {
          setLogicIndex(other.getLogicIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAccountId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.s2s.ClubProxyProto.GoldRoomMsgReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 accountId = 1;
      private long accountId_ ;
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 accountId = 1;</code>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 logicIndex = 2;
      private int logicIndex_ ;
      /**
       * <code>optional int32 logicIndex = 2;</code>
       */
      public boolean hasLogicIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 logicIndex = 2;</code>
       */
      public int getLogicIndex() {
        return logicIndex_;
      }
      /**
       * <code>optional int32 logicIndex = 2;</code>
       */
      public Builder setLogicIndex(int value) {
        bitField0_ |= 0x00000002;
        logicIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 logicIndex = 2;</code>
       */
      public Builder clearLogicIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        logicIndex_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:s2s.GoldRoomMsgReq)
    }

    static {
      defaultInstance = new GoldRoomMsgReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:s2s.GoldRoomMsgReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_s2s_PlayerStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_s2s_PlayerStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_s2s_S2SReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_s2s_S2SReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_s2s_GoldRoomMsgReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_s2s_GoldRoomMsgReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024s2s/Club_Proxy.proto\022\003s2s\"A\n\014PlayerSta" +
      "tus\022\021\n\taccountId\030\001 \002(\003\022\016\n\006status\030\002 \002(\005\022\016" +
      "\n\006roomId\030\003 \001(\005\"8\n\006S2SReq\022\013\n\003cmd\030\001 \002(\005\022!\n" +
      "\006status\030\002 \001(\0132\021.s2s.PlayerStatus\"7\n\016Gold" +
      "RoomMsgReq\022\021\n\taccountId\030\001 \002(\003\022\022\n\nlogicIn" +
      "dex\030\002 \001(\005B$\n\022protobuf.clazz.s2sB\016ClubPro" +
      "xyProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_s2s_PlayerStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_s2s_PlayerStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_s2s_PlayerStatus_descriptor,
              new java.lang.String[] { "AccountId", "Status", "RoomId", });
          internal_static_s2s_S2SReq_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_s2s_S2SReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_s2s_S2SReq_descriptor,
              new java.lang.String[] { "Cmd", "Status", });
          internal_static_s2s_GoldRoomMsgReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_s2s_GoldRoomMsgReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_s2s_GoldRoomMsgReq_descriptor,
              new java.lang.String[] { "AccountId", "LogicIndex", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
