// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mj/huizhou.proto

package protobuf.clazz.mj;

public final class HuiZhou {
  private HuiZhou() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MJ_Hui_ZhouOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> 
        getMsgsList();
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju getMsgs(int index);
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    int getMsgsCount();
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    java.util.List<? extends protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder> 
        getMsgsOrBuilderList();
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder getMsgsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mj.MJ_Hui_Zhou}
   */
  public static final class MJ_Hui_Zhou extends
      com.google.protobuf.GeneratedMessage
      implements MJ_Hui_ZhouOrBuilder {
    // Use MJ_Hui_Zhou.newBuilder() to construct.
    private MJ_Hui_Zhou(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MJ_Hui_Zhou(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MJ_Hui_Zhou defaultInstance;
    public static MJ_Hui_Zhou getDefaultInstance() {
      return defaultInstance;
    }

    public MJ_Hui_Zhou getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MJ_Hui_Zhou(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                msgs_ = new java.util.ArrayList<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju>();
                mutable_bitField0_ |= 0x00000001;
              }
              msgs_.add(input.readMessage(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          msgs_ = java.util.Collections.unmodifiableList(msgs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.class, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.Builder.class);
    }

    public static com.google.protobuf.Parser<MJ_Hui_Zhou> PARSER =
        new com.google.protobuf.AbstractParser<MJ_Hui_Zhou>() {
      public MJ_Hui_Zhou parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MJ_Hui_Zhou(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MJ_Hui_Zhou> getParserForType() {
      return PARSER;
    }

    // repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;
    public static final int MSGS_FIELD_NUMBER = 1;
    private java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> msgs_;
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> getMsgsList() {
      return msgs_;
    }
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public java.util.List<? extends protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder> 
        getMsgsOrBuilderList() {
      return msgs_;
    }
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public int getMsgsCount() {
      return msgs_.size();
    }
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju getMsgs(int index) {
      return msgs_.get(index);
    }
    /**
     * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
     *
     * <pre>
     * </pre>
     */
    public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder getMsgsOrBuilder(
        int index) {
      return msgs_.get(index);
    }

    private void initFields() {
      msgs_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < msgs_.size(); i++) {
        output.writeMessage(1, msgs_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < msgs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, msgs_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.MJ_Hui_Zhou}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.HuiZhou.MJ_Hui_ZhouOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.class, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.Builder.class);
      }

      // Construct using protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (msgsBuilder_ == null) {
          msgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          msgsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_descriptor;
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou getDefaultInstanceForType() {
        return protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.getDefaultInstance();
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou build() {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou buildPartial() {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou result = new protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou(this);
        int from_bitField0_ = bitField0_;
        if (msgsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            msgs_ = java.util.Collections.unmodifiableList(msgs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.msgs_ = msgs_;
        } else {
          result.msgs_ = msgsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou) {
          return mergeFrom((protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou other) {
        if (other == protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou.getDefaultInstance()) return this;
        if (msgsBuilder_ == null) {
          if (!other.msgs_.isEmpty()) {
            if (msgs_.isEmpty()) {
              msgs_ = other.msgs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMsgsIsMutable();
              msgs_.addAll(other.msgs_);
            }
            onChanged();
          }
        } else {
          if (!other.msgs_.isEmpty()) {
            if (msgsBuilder_.isEmpty()) {
              msgsBuilder_.dispose();
              msgsBuilder_ = null;
              msgs_ = other.msgs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              msgsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMsgsFieldBuilder() : null;
            } else {
              msgsBuilder_.addAllMessages(other.msgs_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;
      private java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> msgs_ =
        java.util.Collections.emptyList();
      private void ensureMsgsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          msgs_ = new java.util.ArrayList<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju>(msgs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder> msgsBuilder_;

      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> getMsgsList() {
        if (msgsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(msgs_);
        } else {
          return msgsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public int getMsgsCount() {
        if (msgsBuilder_ == null) {
          return msgs_.size();
        } else {
          return msgsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju getMsgs(int index) {
        if (msgsBuilder_ == null) {
          return msgs_.get(index);
        } else {
          return msgsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setMsgs(
          int index, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju value) {
        if (msgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgsIsMutable();
          msgs_.set(index, value);
          onChanged();
        } else {
          msgsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder setMsgs(
          int index, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder builderForValue) {
        if (msgsBuilder_ == null) {
          ensureMsgsIsMutable();
          msgs_.set(index, builderForValue.build());
          onChanged();
        } else {
          msgsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addMsgs(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju value) {
        if (msgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgsIsMutable();
          msgs_.add(value);
          onChanged();
        } else {
          msgsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addMsgs(
          int index, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju value) {
        if (msgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMsgsIsMutable();
          msgs_.add(index, value);
          onChanged();
        } else {
          msgsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addMsgs(
          protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder builderForValue) {
        if (msgsBuilder_ == null) {
          ensureMsgsIsMutable();
          msgs_.add(builderForValue.build());
          onChanged();
        } else {
          msgsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addMsgs(
          int index, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder builderForValue) {
        if (msgsBuilder_ == null) {
          ensureMsgsIsMutable();
          msgs_.add(index, builderForValue.build());
          onChanged();
        } else {
          msgsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder addAllMsgs(
          java.lang.Iterable<? extends protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju> values) {
        if (msgsBuilder_ == null) {
          ensureMsgsIsMutable();
          super.addAll(values, msgs_);
          onChanged();
        } else {
          msgsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder clearMsgs() {
        if (msgsBuilder_ == null) {
          msgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          msgsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public Builder removeMsgs(int index) {
        if (msgsBuilder_ == null) {
          ensureMsgsIsMutable();
          msgs_.remove(index);
          onChanged();
        } else {
          msgsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder getMsgsBuilder(
          int index) {
        return getMsgsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder getMsgsOrBuilder(
          int index) {
        if (msgsBuilder_ == null) {
          return msgs_.get(index);  } else {
          return msgsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<? extends protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder> 
           getMsgsOrBuilderList() {
        if (msgsBuilder_ != null) {
          return msgsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(msgs_);
        }
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder addMsgsBuilder() {
        return getMsgsFieldBuilder().addBuilder(
            protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder addMsgsBuilder(
          int index) {
        return getMsgsFieldBuilder().addBuilder(
            index, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.MJ_Hui_Zhou_Xiao_Ju msgs = 1;</code>
       *
       * <pre>
       * </pre>
       */
      public java.util.List<protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder> 
           getMsgsBuilderList() {
        return getMsgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder> 
          getMsgsFieldBuilder() {
        if (msgsBuilder_ == null) {
          msgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder>(
                  msgs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          msgs_ = null;
        }
        return msgsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mj.MJ_Hui_Zhou)
    }

    static {
      defaultInstance = new MJ_Hui_Zhou(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.MJ_Hui_Zhou)
  }

  public interface MJ_Hui_Zhou_Xiao_JuOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 fen = 1;
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    java.util.List<java.lang.Integer> getFenList();
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    int getFenCount();
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    int getFen(int index);
  }
  /**
   * Protobuf type {@code mj.MJ_Hui_Zhou_Xiao_Ju}
   */
  public static final class MJ_Hui_Zhou_Xiao_Ju extends
      com.google.protobuf.GeneratedMessage
      implements MJ_Hui_Zhou_Xiao_JuOrBuilder {
    // Use MJ_Hui_Zhou_Xiao_Ju.newBuilder() to construct.
    private MJ_Hui_Zhou_Xiao_Ju(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MJ_Hui_Zhou_Xiao_Ju(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MJ_Hui_Zhou_Xiao_Ju defaultInstance;
    public static MJ_Hui_Zhou_Xiao_Ju getDefaultInstance() {
      return defaultInstance;
    }

    public MJ_Hui_Zhou_Xiao_Ju getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MJ_Hui_Zhou_Xiao_Ju(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                fen_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              fen_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                fen_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                fen_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          fen_ = java.util.Collections.unmodifiableList(fen_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.class, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder.class);
    }

    public static com.google.protobuf.Parser<MJ_Hui_Zhou_Xiao_Ju> PARSER =
        new com.google.protobuf.AbstractParser<MJ_Hui_Zhou_Xiao_Ju>() {
      public MJ_Hui_Zhou_Xiao_Ju parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MJ_Hui_Zhou_Xiao_Ju(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MJ_Hui_Zhou_Xiao_Ju> getParserForType() {
      return PARSER;
    }

    // repeated int32 fen = 1;
    public static final int FEN_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> fen_;
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getFenList() {
      return fen_;
    }
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    public int getFenCount() {
      return fen_.size();
    }
    /**
     * <code>repeated int32 fen = 1;</code>
     *
     * <pre>
     * 每一小局分
     * </pre>
     */
    public int getFen(int index) {
      return fen_.get(index);
    }

    private void initFields() {
      fen_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < fen_.size(); i++) {
        output.writeInt32(1, fen_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < fen_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(fen_.get(i));
        }
        size += dataSize;
        size += 1 * getFenList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.MJ_Hui_Zhou_Xiao_Ju}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_JuOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.class, protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.Builder.class);
      }

      // Construct using protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fen_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.HuiZhou.internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor;
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju getDefaultInstanceForType() {
        return protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.getDefaultInstance();
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju build() {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju buildPartial() {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju result = new protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          fen_ = java.util.Collections.unmodifiableList(fen_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fen_ = fen_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju) {
          return mergeFrom((protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju other) {
        if (other == protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju.getDefaultInstance()) return this;
        if (!other.fen_.isEmpty()) {
          if (fen_.isEmpty()) {
            fen_ = other.fen_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFenIsMutable();
            fen_.addAll(other.fen_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.HuiZhou.MJ_Hui_Zhou_Xiao_Ju) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 fen = 1;
      private java.util.List<java.lang.Integer> fen_ = java.util.Collections.emptyList();
      private void ensureFenIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fen_ = new java.util.ArrayList<java.lang.Integer>(fen_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getFenList() {
        return java.util.Collections.unmodifiableList(fen_);
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public int getFenCount() {
        return fen_.size();
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public int getFen(int index) {
        return fen_.get(index);
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public Builder setFen(
          int index, int value) {
        ensureFenIsMutable();
        fen_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public Builder addFen(int value) {
        ensureFenIsMutable();
        fen_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public Builder addAllFen(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureFenIsMutable();
        super.addAll(values, fen_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 fen = 1;</code>
       *
       * <pre>
       * 每一小局分
       * </pre>
       */
      public Builder clearFen() {
        fen_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.MJ_Hui_Zhou_Xiao_Ju)
    }

    static {
      defaultInstance = new MJ_Hui_Zhou_Xiao_Ju(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.MJ_Hui_Zhou_Xiao_Ju)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_MJ_Hui_Zhou_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_MJ_Hui_Zhou_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mj/huizhou.proto\022\002mj\032\024basic/protocol.p" +
      "roto\"4\n\013MJ_Hui_Zhou\022%\n\004msgs\030\001 \003(\0132\027.mj.M" +
      "J_Hui_Zhou_Xiao_Ju\"\"\n\023MJ_Hui_Zhou_Xiao_J" +
      "u\022\013\n\003fen\030\001 \003(\005B\034\n\021protobuf.clazz.mjB\007Hui" +
      "Zhou"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mj_MJ_Hui_Zhou_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mj_MJ_Hui_Zhou_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_MJ_Hui_Zhou_descriptor,
              new java.lang.String[] { "Msgs", });
          internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_MJ_Hui_Zhou_Xiao_Ju_descriptor,
              new java.lang.String[] { "Fen", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
