// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mj/klds.proto

package protobuf.clazz.mj;

public final class Klds {
  private Klds() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KLDS_PAO_QIAN_EXTOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 zi_ba = 1;
    /**
     * <code>optional int32 zi_ba = 1;</code>
     *
     * <pre>
     *自拔
     * </pre>
     */
    boolean hasZiBa();
    /**
     * <code>optional int32 zi_ba = 1;</code>
     *
     * <pre>
     *自拔
     * </pre>
     */
    int getZiBa();

    // optional int32 duan_men = 2;
    /**
     * <code>optional int32 duan_men = 2;</code>
     *
     * <pre>
     *断门
     * </pre>
     */
    boolean hasDuanMen();
    /**
     * <code>optional int32 duan_men = 2;</code>
     *
     * <pre>
     *断门
     * </pre>
     */
    int getDuanMen();
  }
  /**
   * Protobuf type {@code mj.KLDS_PAO_QIAN_EXT}
   *
   * <pre>
   *窟窿带神跑呛扩展
   * </pre>
   */
  public static final class KLDS_PAO_QIAN_EXT extends
      com.google.protobuf.GeneratedMessage
      implements KLDS_PAO_QIAN_EXTOrBuilder {
    // Use KLDS_PAO_QIAN_EXT.newBuilder() to construct.
    private KLDS_PAO_QIAN_EXT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KLDS_PAO_QIAN_EXT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KLDS_PAO_QIAN_EXT defaultInstance;
    public static KLDS_PAO_QIAN_EXT getDefaultInstance() {
      return defaultInstance;
    }

    public KLDS_PAO_QIAN_EXT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KLDS_PAO_QIAN_EXT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              ziBa_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              duanMen_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.Klds.internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.Klds.internal_static_mj_KLDS_PAO_QIAN_EXT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.class, protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.Builder.class);
    }

    public static com.google.protobuf.Parser<KLDS_PAO_QIAN_EXT> PARSER =
        new com.google.protobuf.AbstractParser<KLDS_PAO_QIAN_EXT>() {
      public KLDS_PAO_QIAN_EXT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KLDS_PAO_QIAN_EXT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KLDS_PAO_QIAN_EXT> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 zi_ba = 1;
    public static final int ZI_BA_FIELD_NUMBER = 1;
    private int ziBa_;
    /**
     * <code>optional int32 zi_ba = 1;</code>
     *
     * <pre>
     *自拔
     * </pre>
     */
    public boolean hasZiBa() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 zi_ba = 1;</code>
     *
     * <pre>
     *自拔
     * </pre>
     */
    public int getZiBa() {
      return ziBa_;
    }

    // optional int32 duan_men = 2;
    public static final int DUAN_MEN_FIELD_NUMBER = 2;
    private int duanMen_;
    /**
     * <code>optional int32 duan_men = 2;</code>
     *
     * <pre>
     *断门
     * </pre>
     */
    public boolean hasDuanMen() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 duan_men = 2;</code>
     *
     * <pre>
     *断门
     * </pre>
     */
    public int getDuanMen() {
      return duanMen_;
    }

    private void initFields() {
      ziBa_ = 0;
      duanMen_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, ziBa_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, duanMen_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, ziBa_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, duanMen_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.KLDS_PAO_QIAN_EXT}
     *
     * <pre>
     *窟窿带神跑呛扩展
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.Klds.internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.Klds.internal_static_mj_KLDS_PAO_QIAN_EXT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.class, protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.Builder.class);
      }

      // Construct using protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ziBa_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        duanMen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.Klds.internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor;
      }

      public protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT getDefaultInstanceForType() {
        return protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.getDefaultInstance();
      }

      public protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT build() {
        protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT buildPartial() {
        protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT result = new protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.ziBa_ = ziBa_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.duanMen_ = duanMen_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT) {
          return mergeFrom((protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT other) {
        if (other == protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT.getDefaultInstance()) return this;
        if (other.hasZiBa()) {
          setZiBa(other.getZiBa());
        }
        if (other.hasDuanMen()) {
          setDuanMen(other.getDuanMen());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.Klds.KLDS_PAO_QIAN_EXT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 zi_ba = 1;
      private int ziBa_ ;
      /**
       * <code>optional int32 zi_ba = 1;</code>
       *
       * <pre>
       *自拔
       * </pre>
       */
      public boolean hasZiBa() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 zi_ba = 1;</code>
       *
       * <pre>
       *自拔
       * </pre>
       */
      public int getZiBa() {
        return ziBa_;
      }
      /**
       * <code>optional int32 zi_ba = 1;</code>
       *
       * <pre>
       *自拔
       * </pre>
       */
      public Builder setZiBa(int value) {
        bitField0_ |= 0x00000001;
        ziBa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 zi_ba = 1;</code>
       *
       * <pre>
       *自拔
       * </pre>
       */
      public Builder clearZiBa() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ziBa_ = 0;
        onChanged();
        return this;
      }

      // optional int32 duan_men = 2;
      private int duanMen_ ;
      /**
       * <code>optional int32 duan_men = 2;</code>
       *
       * <pre>
       *断门
       * </pre>
       */
      public boolean hasDuanMen() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 duan_men = 2;</code>
       *
       * <pre>
       *断门
       * </pre>
       */
      public int getDuanMen() {
        return duanMen_;
      }
      /**
       * <code>optional int32 duan_men = 2;</code>
       *
       * <pre>
       *断门
       * </pre>
       */
      public Builder setDuanMen(int value) {
        bitField0_ |= 0x00000002;
        duanMen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 duan_men = 2;</code>
       *
       * <pre>
       *断门
       * </pre>
       */
      public Builder clearDuanMen() {
        bitField0_ = (bitField0_ & ~0x00000002);
        duanMen_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.KLDS_PAO_QIAN_EXT)
    }

    static {
      defaultInstance = new KLDS_PAO_QIAN_EXT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.KLDS_PAO_QIAN_EXT)
  }

  public interface DingShengOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bool has_sheng = 1;
    /**
     * <code>optional bool has_sheng = 1;</code>
     *
     * <pre>
     *是否有神,
     * </pre>
     */
    boolean hasHasSheng();
    /**
     * <code>optional bool has_sheng = 1;</code>
     *
     * <pre>
     *是否有神,
     * </pre>
     */
    boolean getHasSheng();
  }
  /**
   * Protobuf type {@code mj.DingSheng}
   *
   * <pre>
   *定神操作
   * </pre>
   */
  public static final class DingSheng extends
      com.google.protobuf.GeneratedMessage
      implements DingShengOrBuilder {
    // Use DingSheng.newBuilder() to construct.
    private DingSheng(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DingSheng(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DingSheng defaultInstance;
    public static DingSheng getDefaultInstance() {
      return defaultInstance;
    }

    public DingSheng getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DingSheng(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              hasSheng_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.Klds.internal_static_mj_DingSheng_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.Klds.internal_static_mj_DingSheng_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.Klds.DingSheng.class, protobuf.clazz.mj.Klds.DingSheng.Builder.class);
    }

    public static com.google.protobuf.Parser<DingSheng> PARSER =
        new com.google.protobuf.AbstractParser<DingSheng>() {
      public DingSheng parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DingSheng(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DingSheng> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bool has_sheng = 1;
    public static final int HAS_SHENG_FIELD_NUMBER = 1;
    private boolean hasSheng_;
    /**
     * <code>optional bool has_sheng = 1;</code>
     *
     * <pre>
     *是否有神,
     * </pre>
     */
    public boolean hasHasSheng() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool has_sheng = 1;</code>
     *
     * <pre>
     *是否有神,
     * </pre>
     */
    public boolean getHasSheng() {
      return hasSheng_;
    }

    private void initFields() {
      hasSheng_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, hasSheng_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, hasSheng_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.Klds.DingSheng parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.Klds.DingSheng prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.DingSheng}
     *
     * <pre>
     *定神操作
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.Klds.DingShengOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.Klds.internal_static_mj_DingSheng_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.Klds.internal_static_mj_DingSheng_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.Klds.DingSheng.class, protobuf.clazz.mj.Klds.DingSheng.Builder.class);
      }

      // Construct using protobuf.clazz.mj.Klds.DingSheng.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hasSheng_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.Klds.internal_static_mj_DingSheng_descriptor;
      }

      public protobuf.clazz.mj.Klds.DingSheng getDefaultInstanceForType() {
        return protobuf.clazz.mj.Klds.DingSheng.getDefaultInstance();
      }

      public protobuf.clazz.mj.Klds.DingSheng build() {
        protobuf.clazz.mj.Klds.DingSheng result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.Klds.DingSheng buildPartial() {
        protobuf.clazz.mj.Klds.DingSheng result = new protobuf.clazz.mj.Klds.DingSheng(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hasSheng_ = hasSheng_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.Klds.DingSheng) {
          return mergeFrom((protobuf.clazz.mj.Klds.DingSheng)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.Klds.DingSheng other) {
        if (other == protobuf.clazz.mj.Klds.DingSheng.getDefaultInstance()) return this;
        if (other.hasHasSheng()) {
          setHasSheng(other.getHasSheng());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.Klds.DingSheng parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.Klds.DingSheng) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bool has_sheng = 1;
      private boolean hasSheng_ ;
      /**
       * <code>optional bool has_sheng = 1;</code>
       *
       * <pre>
       *是否有神,
       * </pre>
       */
      public boolean hasHasSheng() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool has_sheng = 1;</code>
       *
       * <pre>
       *是否有神,
       * </pre>
       */
      public boolean getHasSheng() {
        return hasSheng_;
      }
      /**
       * <code>optional bool has_sheng = 1;</code>
       *
       * <pre>
       *是否有神,
       * </pre>
       */
      public Builder setHasSheng(boolean value) {
        bitField0_ |= 0x00000001;
        hasSheng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool has_sheng = 1;</code>
       *
       * <pre>
       *是否有神,
       * </pre>
       */
      public Builder clearHasSheng() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hasSheng_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.DingSheng)
    }

    static {
      defaultInstance = new DingSheng(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.DingSheng)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_KLDS_PAO_QIAN_EXT_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_DingSheng_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_DingSheng_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmj/klds.proto\022\002mj\032\024basic/protocol.prot" +
      "o\"4\n\021KLDS_PAO_QIAN_EXT\022\r\n\005zi_ba\030\001 \001(\005\022\020\n" +
      "\010duan_men\030\002 \001(\005\"\036\n\tDingSheng\022\021\n\thas_shen" +
      "g\030\001 \001(\010B\031\n\021protobuf.clazz.mjB\004Klds"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mj_KLDS_PAO_QIAN_EXT_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_KLDS_PAO_QIAN_EXT_descriptor,
              new java.lang.String[] { "ZiBa", "DuanMen", });
          internal_static_mj_DingSheng_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mj_DingSheng_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_DingSheng_descriptor,
              new java.lang.String[] { "HasSheng", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
