// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mj/kwx.proto

package protobuf.clazz.mj;

public final class KwxProto {
  private KwxProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KWXLiangCardOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 operate_card = 1;
    /**
     * <code>optional int32 operate_card = 1;</code>
     *
     * <pre>
     *亮张叫口牌
     * </pre>
     */
    boolean hasOperateCard();
    /**
     * <code>optional int32 operate_card = 1;</code>
     *
     * <pre>
     *亮张叫口牌
     * </pre>
     */
    int getOperateCard();

    // optional int32 operate_code = 2;
    /**
     * <code>optional int32 operate_code = 2;</code>
     *
     * <pre>
     *操作指令  WIK_LIANG = 0x400
     * </pre>
     */
    boolean hasOperateCode();
    /**
     * <code>optional int32 operate_code = 2;</code>
     *
     * <pre>
     *操作指令  WIK_LIANG = 0x400
     * </pre>
     */
    int getOperateCode();

    // repeated int32 kou_cards = 3;
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    java.util.List<java.lang.Integer> getKouCardsList();
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    int getKouCardsCount();
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    int getKouCards(int index);

    // optional int32 kou_count = 4;
    /**
     * <code>optional int32 kou_count = 4;</code>
     *
     * <pre>
     *扣牌数量
     * </pre>
     */
    boolean hasKouCount();
    /**
     * <code>optional int32 kou_count = 4;</code>
     *
     * <pre>
     *扣牌数量
     * </pre>
     */
    int getKouCount();
  }
  /**
   * Protobuf type {@code mj.KWXLiangCard}
   *
   * <pre>
   * 亮牌
   * </pre>
   */
  public static final class KWXLiangCard extends
      com.google.protobuf.GeneratedMessage
      implements KWXLiangCardOrBuilder {
    // Use KWXLiangCard.newBuilder() to construct.
    private KWXLiangCard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KWXLiangCard(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KWXLiangCard defaultInstance;
    public static KWXLiangCard getDefaultInstance() {
      return defaultInstance;
    }

    public KWXLiangCard getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KWXLiangCard(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              operateCard_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              operateCode_ = input.readInt32();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                kouCards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              kouCards_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                kouCards_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                kouCards_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              kouCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          kouCards_ = java.util.Collections.unmodifiableList(kouCards_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_KWXLiangCard_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_KWXLiangCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.KwxProto.KWXLiangCard.class, protobuf.clazz.mj.KwxProto.KWXLiangCard.Builder.class);
    }

    public static com.google.protobuf.Parser<KWXLiangCard> PARSER =
        new com.google.protobuf.AbstractParser<KWXLiangCard>() {
      public KWXLiangCard parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KWXLiangCard(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KWXLiangCard> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 operate_card = 1;
    public static final int OPERATE_CARD_FIELD_NUMBER = 1;
    private int operateCard_;
    /**
     * <code>optional int32 operate_card = 1;</code>
     *
     * <pre>
     *亮张叫口牌
     * </pre>
     */
    public boolean hasOperateCard() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 operate_card = 1;</code>
     *
     * <pre>
     *亮张叫口牌
     * </pre>
     */
    public int getOperateCard() {
      return operateCard_;
    }

    // optional int32 operate_code = 2;
    public static final int OPERATE_CODE_FIELD_NUMBER = 2;
    private int operateCode_;
    /**
     * <code>optional int32 operate_code = 2;</code>
     *
     * <pre>
     *操作指令  WIK_LIANG = 0x400
     * </pre>
     */
    public boolean hasOperateCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 operate_code = 2;</code>
     *
     * <pre>
     *操作指令  WIK_LIANG = 0x400
     * </pre>
     */
    public int getOperateCode() {
      return operateCode_;
    }

    // repeated int32 kou_cards = 3;
    public static final int KOU_CARDS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> kouCards_;
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getKouCardsList() {
      return kouCards_;
    }
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    public int getKouCardsCount() {
      return kouCards_.size();
    }
    /**
     * <code>repeated int32 kou_cards = 3;</code>
     *
     * <pre>
     * 亮扣的牌
     * </pre>
     */
    public int getKouCards(int index) {
      return kouCards_.get(index);
    }

    // optional int32 kou_count = 4;
    public static final int KOU_COUNT_FIELD_NUMBER = 4;
    private int kouCount_;
    /**
     * <code>optional int32 kou_count = 4;</code>
     *
     * <pre>
     *扣牌数量
     * </pre>
     */
    public boolean hasKouCount() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 kou_count = 4;</code>
     *
     * <pre>
     *扣牌数量
     * </pre>
     */
    public int getKouCount() {
      return kouCount_;
    }

    private void initFields() {
      operateCard_ = 0;
      operateCode_ = 0;
      kouCards_ = java.util.Collections.emptyList();
      kouCount_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, operateCard_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, operateCode_);
      }
      for (int i = 0; i < kouCards_.size(); i++) {
        output.writeInt32(3, kouCards_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, kouCount_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, operateCard_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, operateCode_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < kouCards_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(kouCards_.get(i));
        }
        size += dataSize;
        size += 1 * getKouCardsList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, kouCount_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.KWXLiangCard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.KwxProto.KWXLiangCard prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.KWXLiangCard}
     *
     * <pre>
     * 亮牌
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.KwxProto.KWXLiangCardOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_KWXLiangCard_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_KWXLiangCard_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.KwxProto.KWXLiangCard.class, protobuf.clazz.mj.KwxProto.KWXLiangCard.Builder.class);
      }

      // Construct using protobuf.clazz.mj.KwxProto.KWXLiangCard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        operateCard_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        operateCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        kouCards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        kouCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_KWXLiangCard_descriptor;
      }

      public protobuf.clazz.mj.KwxProto.KWXLiangCard getDefaultInstanceForType() {
        return protobuf.clazz.mj.KwxProto.KWXLiangCard.getDefaultInstance();
      }

      public protobuf.clazz.mj.KwxProto.KWXLiangCard build() {
        protobuf.clazz.mj.KwxProto.KWXLiangCard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.KwxProto.KWXLiangCard buildPartial() {
        protobuf.clazz.mj.KwxProto.KWXLiangCard result = new protobuf.clazz.mj.KwxProto.KWXLiangCard(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operateCard_ = operateCard_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.operateCode_ = operateCode_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          kouCards_ = java.util.Collections.unmodifiableList(kouCards_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.kouCards_ = kouCards_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.kouCount_ = kouCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.KwxProto.KWXLiangCard) {
          return mergeFrom((protobuf.clazz.mj.KwxProto.KWXLiangCard)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.KwxProto.KWXLiangCard other) {
        if (other == protobuf.clazz.mj.KwxProto.KWXLiangCard.getDefaultInstance()) return this;
        if (other.hasOperateCard()) {
          setOperateCard(other.getOperateCard());
        }
        if (other.hasOperateCode()) {
          setOperateCode(other.getOperateCode());
        }
        if (!other.kouCards_.isEmpty()) {
          if (kouCards_.isEmpty()) {
            kouCards_ = other.kouCards_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureKouCardsIsMutable();
            kouCards_.addAll(other.kouCards_);
          }
          onChanged();
        }
        if (other.hasKouCount()) {
          setKouCount(other.getKouCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.KwxProto.KWXLiangCard parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.KwxProto.KWXLiangCard) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 operate_card = 1;
      private int operateCard_ ;
      /**
       * <code>optional int32 operate_card = 1;</code>
       *
       * <pre>
       *亮张叫口牌
       * </pre>
       */
      public boolean hasOperateCard() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 operate_card = 1;</code>
       *
       * <pre>
       *亮张叫口牌
       * </pre>
       */
      public int getOperateCard() {
        return operateCard_;
      }
      /**
       * <code>optional int32 operate_card = 1;</code>
       *
       * <pre>
       *亮张叫口牌
       * </pre>
       */
      public Builder setOperateCard(int value) {
        bitField0_ |= 0x00000001;
        operateCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 operate_card = 1;</code>
       *
       * <pre>
       *亮张叫口牌
       * </pre>
       */
      public Builder clearOperateCard() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operateCard_ = 0;
        onChanged();
        return this;
      }

      // optional int32 operate_code = 2;
      private int operateCode_ ;
      /**
       * <code>optional int32 operate_code = 2;</code>
       *
       * <pre>
       *操作指令  WIK_LIANG = 0x400
       * </pre>
       */
      public boolean hasOperateCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 operate_code = 2;</code>
       *
       * <pre>
       *操作指令  WIK_LIANG = 0x400
       * </pre>
       */
      public int getOperateCode() {
        return operateCode_;
      }
      /**
       * <code>optional int32 operate_code = 2;</code>
       *
       * <pre>
       *操作指令  WIK_LIANG = 0x400
       * </pre>
       */
      public Builder setOperateCode(int value) {
        bitField0_ |= 0x00000002;
        operateCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 operate_code = 2;</code>
       *
       * <pre>
       *操作指令  WIK_LIANG = 0x400
       * </pre>
       */
      public Builder clearOperateCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operateCode_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 kou_cards = 3;
      private java.util.List<java.lang.Integer> kouCards_ = java.util.Collections.emptyList();
      private void ensureKouCardsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          kouCards_ = new java.util.ArrayList<java.lang.Integer>(kouCards_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getKouCardsList() {
        return java.util.Collections.unmodifiableList(kouCards_);
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public int getKouCardsCount() {
        return kouCards_.size();
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public int getKouCards(int index) {
        return kouCards_.get(index);
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public Builder setKouCards(
          int index, int value) {
        ensureKouCardsIsMutable();
        kouCards_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public Builder addKouCards(int value) {
        ensureKouCardsIsMutable();
        kouCards_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public Builder addAllKouCards(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureKouCardsIsMutable();
        super.addAll(values, kouCards_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 kou_cards = 3;</code>
       *
       * <pre>
       * 亮扣的牌
       * </pre>
       */
      public Builder clearKouCards() {
        kouCards_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // optional int32 kou_count = 4;
      private int kouCount_ ;
      /**
       * <code>optional int32 kou_count = 4;</code>
       *
       * <pre>
       *扣牌数量
       * </pre>
       */
      public boolean hasKouCount() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 kou_count = 4;</code>
       *
       * <pre>
       *扣牌数量
       * </pre>
       */
      public int getKouCount() {
        return kouCount_;
      }
      /**
       * <code>optional int32 kou_count = 4;</code>
       *
       * <pre>
       *扣牌数量
       * </pre>
       */
      public Builder setKouCount(int value) {
        bitField0_ |= 0x00000008;
        kouCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 kou_count = 4;</code>
       *
       * <pre>
       *扣牌数量
       * </pre>
       */
      public Builder clearKouCount() {
        bitField0_ = (bitField0_ & ~0x00000008);
        kouCount_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.KWXLiangCard)
    }

    static {
      defaultInstance = new KWXLiangCard(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.KWXLiangCard)
  }

  public interface DZMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .Int32ArrayResponse card = 1;
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse> 
        getCardList();
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    protobuf.clazz.Protocol.Int32ArrayResponse getCard(int index);
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    int getCardCount();
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    java.util.List<? extends protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder> 
        getCardOrBuilderList();
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder getCardOrBuilder(
        int index);

    // optional int32 end_chu_zi = 2;
    /**
     * <code>optional int32 end_chu_zi = 2;</code>
     *
     * <pre>
     * 出子借宿
     * </pre>
     */
    boolean hasEndChuZi();
    /**
     * <code>optional int32 end_chu_zi = 2;</code>
     *
     * <pre>
     * 出子借宿
     * </pre>
     */
    int getEndChuZi();
  }
  /**
   * Protobuf type {@code mj.DZMessage}
   */
  public static final class DZMessage extends
      com.google.protobuf.GeneratedMessage
      implements DZMessageOrBuilder {
    // Use DZMessage.newBuilder() to construct.
    private DZMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DZMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DZMessage defaultInstance;
    public static DZMessage getDefaultInstance() {
      return defaultInstance;
    }

    public DZMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DZMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                card_ = new java.util.ArrayList<protobuf.clazz.Protocol.Int32ArrayResponse>();
                mutable_bitField0_ |= 0x00000001;
              }
              card_.add(input.readMessage(protobuf.clazz.Protocol.Int32ArrayResponse.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              endChuZi_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          card_ = java.util.Collections.unmodifiableList(card_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_DZMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_DZMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.KwxProto.DZMessage.class, protobuf.clazz.mj.KwxProto.DZMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<DZMessage> PARSER =
        new com.google.protobuf.AbstractParser<DZMessage>() {
      public DZMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DZMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DZMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .Int32ArrayResponse card = 1;
    public static final int CARD_FIELD_NUMBER = 1;
    private java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse> card_;
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse> getCardList() {
      return card_;
    }
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public java.util.List<? extends protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder> 
        getCardOrBuilderList() {
      return card_;
    }
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public int getCardCount() {
      return card_.size();
    }
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public protobuf.clazz.Protocol.Int32ArrayResponse getCard(int index) {
      return card_.get(index);
    }
    /**
     * <code>repeated .Int32ArrayResponse card = 1;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder getCardOrBuilder(
        int index) {
      return card_.get(index);
    }

    // optional int32 end_chu_zi = 2;
    public static final int END_CHU_ZI_FIELD_NUMBER = 2;
    private int endChuZi_;
    /**
     * <code>optional int32 end_chu_zi = 2;</code>
     *
     * <pre>
     * 出子借宿
     * </pre>
     */
    public boolean hasEndChuZi() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 end_chu_zi = 2;</code>
     *
     * <pre>
     * 出子借宿
     * </pre>
     */
    public int getEndChuZi() {
      return endChuZi_;
    }

    private void initFields() {
      card_ = java.util.Collections.emptyList();
      endChuZi_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < card_.size(); i++) {
        output.writeMessage(1, card_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, endChuZi_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < card_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, card_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, endChuZi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.DZMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.KwxProto.DZMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.DZMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.KwxProto.DZMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_DZMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_DZMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.KwxProto.DZMessage.class, protobuf.clazz.mj.KwxProto.DZMessage.Builder.class);
      }

      // Construct using protobuf.clazz.mj.KwxProto.DZMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCardFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cardBuilder_ == null) {
          card_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cardBuilder_.clear();
        }
        endChuZi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_DZMessage_descriptor;
      }

      public protobuf.clazz.mj.KwxProto.DZMessage getDefaultInstanceForType() {
        return protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance();
      }

      public protobuf.clazz.mj.KwxProto.DZMessage build() {
        protobuf.clazz.mj.KwxProto.DZMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.KwxProto.DZMessage buildPartial() {
        protobuf.clazz.mj.KwxProto.DZMessage result = new protobuf.clazz.mj.KwxProto.DZMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (cardBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            card_ = java.util.Collections.unmodifiableList(card_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.card_ = card_;
        } else {
          result.card_ = cardBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.endChuZi_ = endChuZi_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.KwxProto.DZMessage) {
          return mergeFrom((protobuf.clazz.mj.KwxProto.DZMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.KwxProto.DZMessage other) {
        if (other == protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance()) return this;
        if (cardBuilder_ == null) {
          if (!other.card_.isEmpty()) {
            if (card_.isEmpty()) {
              card_ = other.card_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCardIsMutable();
              card_.addAll(other.card_);
            }
            onChanged();
          }
        } else {
          if (!other.card_.isEmpty()) {
            if (cardBuilder_.isEmpty()) {
              cardBuilder_.dispose();
              cardBuilder_ = null;
              card_ = other.card_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cardBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCardFieldBuilder() : null;
            } else {
              cardBuilder_.addAllMessages(other.card_);
            }
          }
        }
        if (other.hasEndChuZi()) {
          setEndChuZi(other.getEndChuZi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.KwxProto.DZMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.KwxProto.DZMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .Int32ArrayResponse card = 1;
      private java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse> card_ =
        java.util.Collections.emptyList();
      private void ensureCardIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          card_ = new java.util.ArrayList<protobuf.clazz.Protocol.Int32ArrayResponse>(card_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.Protocol.Int32ArrayResponse, protobuf.clazz.Protocol.Int32ArrayResponse.Builder, protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder> cardBuilder_;

      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse> getCardList() {
        if (cardBuilder_ == null) {
          return java.util.Collections.unmodifiableList(card_);
        } else {
          return cardBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public int getCardCount() {
        if (cardBuilder_ == null) {
          return card_.size();
        } else {
          return cardBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public protobuf.clazz.Protocol.Int32ArrayResponse getCard(int index) {
        if (cardBuilder_ == null) {
          return card_.get(index);
        } else {
          return cardBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder setCard(
          int index, protobuf.clazz.Protocol.Int32ArrayResponse value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.set(index, value);
          onChanged();
        } else {
          cardBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder setCard(
          int index, protobuf.clazz.Protocol.Int32ArrayResponse.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.set(index, builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addCard(protobuf.clazz.Protocol.Int32ArrayResponse value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.add(value);
          onChanged();
        } else {
          cardBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addCard(
          int index, protobuf.clazz.Protocol.Int32ArrayResponse value) {
        if (cardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCardIsMutable();
          card_.add(index, value);
          onChanged();
        } else {
          cardBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addCard(
          protobuf.clazz.Protocol.Int32ArrayResponse.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.add(builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addCard(
          int index, protobuf.clazz.Protocol.Int32ArrayResponse.Builder builderForValue) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.add(index, builderForValue.build());
          onChanged();
        } else {
          cardBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addAllCard(
          java.lang.Iterable<? extends protobuf.clazz.Protocol.Int32ArrayResponse> values) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          super.addAll(values, card_);
          onChanged();
        } else {
          cardBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder clearCard() {
        if (cardBuilder_ == null) {
          card_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cardBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder removeCard(int index) {
        if (cardBuilder_ == null) {
          ensureCardIsMutable();
          card_.remove(index);
          onChanged();
        } else {
          cardBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public protobuf.clazz.Protocol.Int32ArrayResponse.Builder getCardBuilder(
          int index) {
        return getCardFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder getCardOrBuilder(
          int index) {
        if (cardBuilder_ == null) {
          return card_.get(index);  } else {
          return cardBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public java.util.List<? extends protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder> 
           getCardOrBuilderList() {
        if (cardBuilder_ != null) {
          return cardBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(card_);
        }
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public protobuf.clazz.Protocol.Int32ArrayResponse.Builder addCardBuilder() {
        return getCardFieldBuilder().addBuilder(
            protobuf.clazz.Protocol.Int32ArrayResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public protobuf.clazz.Protocol.Int32ArrayResponse.Builder addCardBuilder(
          int index) {
        return getCardFieldBuilder().addBuilder(
            index, protobuf.clazz.Protocol.Int32ArrayResponse.getDefaultInstance());
      }
      /**
       * <code>repeated .Int32ArrayResponse card = 1;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public java.util.List<protobuf.clazz.Protocol.Int32ArrayResponse.Builder> 
           getCardBuilderList() {
        return getCardFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.Protocol.Int32ArrayResponse, protobuf.clazz.Protocol.Int32ArrayResponse.Builder, protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder> 
          getCardFieldBuilder() {
        if (cardBuilder_ == null) {
          cardBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.clazz.Protocol.Int32ArrayResponse, protobuf.clazz.Protocol.Int32ArrayResponse.Builder, protobuf.clazz.Protocol.Int32ArrayResponseOrBuilder>(
                  card_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          card_ = null;
        }
        return cardBuilder_;
      }

      // optional int32 end_chu_zi = 2;
      private int endChuZi_ ;
      /**
       * <code>optional int32 end_chu_zi = 2;</code>
       *
       * <pre>
       * 出子借宿
       * </pre>
       */
      public boolean hasEndChuZi() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 end_chu_zi = 2;</code>
       *
       * <pre>
       * 出子借宿
       * </pre>
       */
      public int getEndChuZi() {
        return endChuZi_;
      }
      /**
       * <code>optional int32 end_chu_zi = 2;</code>
       *
       * <pre>
       * 出子借宿
       * </pre>
       */
      public Builder setEndChuZi(int value) {
        bitField0_ |= 0x00000002;
        endChuZi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 end_chu_zi = 2;</code>
       *
       * <pre>
       * 出子借宿
       * </pre>
       */
      public Builder clearEndChuZi() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endChuZi_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.DZMessage)
    }

    static {
      defaultInstance = new DZMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.DZMessage)
  }

  public interface PlayerDZMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 status = 1;
    /**
     * <code>optional int32 status = 1;</code>
     *
     * <pre>
     * 出子状态。0：未出子，1：已出子
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 1;</code>
     *
     * <pre>
     * 出子状态。0：未出子，1：已出子
     * </pre>
     */
    int getStatus();

    // repeated int32 view_card = 2;
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    java.util.List<java.lang.Integer> getViewCardList();
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    int getViewCardCount();
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    int getViewCard(int index);

    // repeated int32 can_card = 3;
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    java.util.List<java.lang.Integer> getCanCardList();
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    int getCanCardCount();
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    int getCanCard(int index);

    // required int32 type = 4;
    /**
     * <code>required int32 type = 4;</code>
     *
     * <pre>
     * 1: 请求出子, 2：获取已出子信息
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 4;</code>
     *
     * <pre>
     * 1: 请求出子, 2：获取已出子信息
     * </pre>
     */
    int getType();

    // optional .mj.DZMessage dzMessage = 5;
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    boolean hasDzMessage();
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    protobuf.clazz.mj.KwxProto.DZMessage getDzMessage();
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    protobuf.clazz.mj.KwxProto.DZMessageOrBuilder getDzMessageOrBuilder();
  }
  /**
   * Protobuf type {@code mj.PlayerDZMessage}
   */
  public static final class PlayerDZMessage extends
      com.google.protobuf.GeneratedMessage
      implements PlayerDZMessageOrBuilder {
    // Use PlayerDZMessage.newBuilder() to construct.
    private PlayerDZMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerDZMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerDZMessage defaultInstance;
    public static PlayerDZMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerDZMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerDZMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                viewCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              viewCard_.add(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                viewCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                viewCard_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                canCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              canCard_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                canCard_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                canCard_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 32: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 42: {
              protobuf.clazz.mj.KwxProto.DZMessage.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = dzMessage_.toBuilder();
              }
              dzMessage_ = input.readMessage(protobuf.clazz.mj.KwxProto.DZMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dzMessage_);
                dzMessage_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          viewCard_ = java.util.Collections.unmodifiableList(viewCard_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          canCard_ = java.util.Collections.unmodifiableList(canCard_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_PlayerDZMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.KwxProto.internal_static_mj_PlayerDZMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.KwxProto.PlayerDZMessage.class, protobuf.clazz.mj.KwxProto.PlayerDZMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerDZMessage> PARSER =
        new com.google.protobuf.AbstractParser<PlayerDZMessage>() {
      public PlayerDZMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerDZMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerDZMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 status = 1;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>optional int32 status = 1;</code>
     *
     * <pre>
     * 出子状态。0：未出子，1：已出子
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 status = 1;</code>
     *
     * <pre>
     * 出子状态。0：未出子，1：已出子
     * </pre>
     */
    public int getStatus() {
      return status_;
    }

    // repeated int32 view_card = 2;
    public static final int VIEW_CARD_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> viewCard_;
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getViewCardList() {
      return viewCard_;
    }
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    public int getViewCardCount() {
      return viewCard_.size();
    }
    /**
     * <code>repeated int32 view_card = 2;</code>
     *
     * <pre>
     * 面板上的子
     * </pre>
     */
    public int getViewCard(int index) {
      return viewCard_.get(index);
    }

    // repeated int32 can_card = 3;
    public static final int CAN_CARD_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> canCard_;
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getCanCardList() {
      return canCard_;
    }
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public int getCanCardCount() {
      return canCard_.size();
    }
    /**
     * <code>repeated int32 can_card = 3;</code>
     *
     * <pre>
     * 已选择的子
     * </pre>
     */
    public int getCanCard(int index) {
      return canCard_.get(index);
    }

    // required int32 type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>required int32 type = 4;</code>
     *
     * <pre>
     * 1: 请求出子, 2：获取已出子信息
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 4;</code>
     *
     * <pre>
     * 1: 请求出子, 2：获取已出子信息
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // optional .mj.DZMessage dzMessage = 5;
    public static final int DZMESSAGE_FIELD_NUMBER = 5;
    private protobuf.clazz.mj.KwxProto.DZMessage dzMessage_;
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    public boolean hasDzMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    public protobuf.clazz.mj.KwxProto.DZMessage getDzMessage() {
      return dzMessage_;
    }
    /**
     * <code>optional .mj.DZMessage dzMessage = 5;</code>
     *
     * <pre>
     * 已出子信息
     * </pre>
     */
    public protobuf.clazz.mj.KwxProto.DZMessageOrBuilder getDzMessageOrBuilder() {
      return dzMessage_;
    }

    private void initFields() {
      status_ = 0;
      viewCard_ = java.util.Collections.emptyList();
      canCard_ = java.util.Collections.emptyList();
      type_ = 0;
      dzMessage_ = protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, status_);
      }
      for (int i = 0; i < viewCard_.size(); i++) {
        output.writeInt32(2, viewCard_.get(i));
      }
      for (int i = 0; i < canCard_.size(); i++) {
        output.writeInt32(3, canCard_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(4, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(5, dzMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, status_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < viewCard_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(viewCard_.get(i));
        }
        size += dataSize;
        size += 1 * getViewCardList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < canCard_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(canCard_.get(i));
        }
        size += dataSize;
        size += 1 * getCanCardList().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, dzMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.KwxProto.PlayerDZMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.KwxProto.PlayerDZMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.PlayerDZMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.KwxProto.PlayerDZMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_PlayerDZMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_PlayerDZMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.KwxProto.PlayerDZMessage.class, protobuf.clazz.mj.KwxProto.PlayerDZMessage.Builder.class);
      }

      // Construct using protobuf.clazz.mj.KwxProto.PlayerDZMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDzMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        viewCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        canCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (dzMessageBuilder_ == null) {
          dzMessage_ = protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance();
        } else {
          dzMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.KwxProto.internal_static_mj_PlayerDZMessage_descriptor;
      }

      public protobuf.clazz.mj.KwxProto.PlayerDZMessage getDefaultInstanceForType() {
        return protobuf.clazz.mj.KwxProto.PlayerDZMessage.getDefaultInstance();
      }

      public protobuf.clazz.mj.KwxProto.PlayerDZMessage build() {
        protobuf.clazz.mj.KwxProto.PlayerDZMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.KwxProto.PlayerDZMessage buildPartial() {
        protobuf.clazz.mj.KwxProto.PlayerDZMessage result = new protobuf.clazz.mj.KwxProto.PlayerDZMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          viewCard_ = java.util.Collections.unmodifiableList(viewCard_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.viewCard_ = viewCard_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          canCard_ = java.util.Collections.unmodifiableList(canCard_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.canCard_ = canCard_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000004;
        }
        if (dzMessageBuilder_ == null) {
          result.dzMessage_ = dzMessage_;
        } else {
          result.dzMessage_ = dzMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.KwxProto.PlayerDZMessage) {
          return mergeFrom((protobuf.clazz.mj.KwxProto.PlayerDZMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.KwxProto.PlayerDZMessage other) {
        if (other == protobuf.clazz.mj.KwxProto.PlayerDZMessage.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (!other.viewCard_.isEmpty()) {
          if (viewCard_.isEmpty()) {
            viewCard_ = other.viewCard_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureViewCardIsMutable();
            viewCard_.addAll(other.viewCard_);
          }
          onChanged();
        }
        if (!other.canCard_.isEmpty()) {
          if (canCard_.isEmpty()) {
            canCard_ = other.canCard_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCanCardIsMutable();
            canCard_.addAll(other.canCard_);
          }
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasDzMessage()) {
          mergeDzMessage(other.getDzMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.KwxProto.PlayerDZMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.KwxProto.PlayerDZMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 status = 1;
      private int status_ ;
      /**
       * <code>optional int32 status = 1;</code>
       *
       * <pre>
       * 出子状态。0：未出子，1：已出子
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 status = 1;</code>
       *
       * <pre>
       * 出子状态。0：未出子，1：已出子
       * </pre>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 1;</code>
       *
       * <pre>
       * 出子状态。0：未出子，1：已出子
       * </pre>
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000001;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 1;</code>
       *
       * <pre>
       * 出子状态。0：未出子，1：已出子
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      // repeated int32 view_card = 2;
      private java.util.List<java.lang.Integer> viewCard_ = java.util.Collections.emptyList();
      private void ensureViewCardIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          viewCard_ = new java.util.ArrayList<java.lang.Integer>(viewCard_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getViewCardList() {
        return java.util.Collections.unmodifiableList(viewCard_);
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public int getViewCardCount() {
        return viewCard_.size();
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public int getViewCard(int index) {
        return viewCard_.get(index);
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public Builder setViewCard(
          int index, int value) {
        ensureViewCardIsMutable();
        viewCard_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public Builder addViewCard(int value) {
        ensureViewCardIsMutable();
        viewCard_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public Builder addAllViewCard(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureViewCardIsMutable();
        super.addAll(values, viewCard_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 view_card = 2;</code>
       *
       * <pre>
       * 面板上的子
       * </pre>
       */
      public Builder clearViewCard() {
        viewCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // repeated int32 can_card = 3;
      private java.util.List<java.lang.Integer> canCard_ = java.util.Collections.emptyList();
      private void ensureCanCardIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          canCard_ = new java.util.ArrayList<java.lang.Integer>(canCard_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getCanCardList() {
        return java.util.Collections.unmodifiableList(canCard_);
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public int getCanCardCount() {
        return canCard_.size();
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public int getCanCard(int index) {
        return canCard_.get(index);
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder setCanCard(
          int index, int value) {
        ensureCanCardIsMutable();
        canCard_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addCanCard(int value) {
        ensureCanCardIsMutable();
        canCard_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder addAllCanCard(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCanCardIsMutable();
        super.addAll(values, canCard_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 can_card = 3;</code>
       *
       * <pre>
       * 已选择的子
       * </pre>
       */
      public Builder clearCanCard() {
        canCard_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }

      // required int32 type = 4;
      private int type_ ;
      /**
       * <code>required int32 type = 4;</code>
       *
       * <pre>
       * 1: 请求出子, 2：获取已出子信息
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 type = 4;</code>
       *
       * <pre>
       * 1: 请求出子, 2：获取已出子信息
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 4;</code>
       *
       * <pre>
       * 1: 请求出子, 2：获取已出子信息
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 4;</code>
       *
       * <pre>
       * 1: 请求出子, 2：获取已出子信息
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional .mj.DZMessage dzMessage = 5;
      private protobuf.clazz.mj.KwxProto.DZMessage dzMessage_ = protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.clazz.mj.KwxProto.DZMessage, protobuf.clazz.mj.KwxProto.DZMessage.Builder, protobuf.clazz.mj.KwxProto.DZMessageOrBuilder> dzMessageBuilder_;
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public boolean hasDzMessage() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public protobuf.clazz.mj.KwxProto.DZMessage getDzMessage() {
        if (dzMessageBuilder_ == null) {
          return dzMessage_;
        } else {
          return dzMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public Builder setDzMessage(protobuf.clazz.mj.KwxProto.DZMessage value) {
        if (dzMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dzMessage_ = value;
          onChanged();
        } else {
          dzMessageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public Builder setDzMessage(
          protobuf.clazz.mj.KwxProto.DZMessage.Builder builderForValue) {
        if (dzMessageBuilder_ == null) {
          dzMessage_ = builderForValue.build();
          onChanged();
        } else {
          dzMessageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public Builder mergeDzMessage(protobuf.clazz.mj.KwxProto.DZMessage value) {
        if (dzMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              dzMessage_ != protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance()) {
            dzMessage_ =
              protobuf.clazz.mj.KwxProto.DZMessage.newBuilder(dzMessage_).mergeFrom(value).buildPartial();
          } else {
            dzMessage_ = value;
          }
          onChanged();
        } else {
          dzMessageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public Builder clearDzMessage() {
        if (dzMessageBuilder_ == null) {
          dzMessage_ = protobuf.clazz.mj.KwxProto.DZMessage.getDefaultInstance();
          onChanged();
        } else {
          dzMessageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public protobuf.clazz.mj.KwxProto.DZMessage.Builder getDzMessageBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getDzMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      public protobuf.clazz.mj.KwxProto.DZMessageOrBuilder getDzMessageOrBuilder() {
        if (dzMessageBuilder_ != null) {
          return dzMessageBuilder_.getMessageOrBuilder();
        } else {
          return dzMessage_;
        }
      }
      /**
       * <code>optional .mj.DZMessage dzMessage = 5;</code>
       *
       * <pre>
       * 已出子信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          protobuf.clazz.mj.KwxProto.DZMessage, protobuf.clazz.mj.KwxProto.DZMessage.Builder, protobuf.clazz.mj.KwxProto.DZMessageOrBuilder> 
          getDzMessageFieldBuilder() {
        if (dzMessageBuilder_ == null) {
          dzMessageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              protobuf.clazz.mj.KwxProto.DZMessage, protobuf.clazz.mj.KwxProto.DZMessage.Builder, protobuf.clazz.mj.KwxProto.DZMessageOrBuilder>(
                  dzMessage_,
                  getParentForChildren(),
                  isClean());
          dzMessage_ = null;
        }
        return dzMessageBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mj.PlayerDZMessage)
    }

    static {
      defaultInstance = new PlayerDZMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.PlayerDZMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_KWXLiangCard_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_KWXLiangCard_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_DZMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_DZMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_PlayerDZMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_PlayerDZMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mj/kwx.proto\022\002mj\032\024basic/protocol.proto" +
      "\"`\n\014KWXLiangCard\022\024\n\014operate_card\030\001 \001(\005\022\024" +
      "\n\014operate_code\030\002 \001(\005\022\021\n\tkou_cards\030\003 \003(\005\022" +
      "\021\n\tkou_count\030\004 \001(\005\"B\n\tDZMessage\022!\n\004card\030" +
      "\001 \003(\0132\023.Int32ArrayResponse\022\022\n\nend_chu_zi" +
      "\030\002 \001(\005\"v\n\017PlayerDZMessage\022\016\n\006status\030\001 \001(" +
      "\005\022\021\n\tview_card\030\002 \003(\005\022\020\n\010can_card\030\003 \003(\005\022\014" +
      "\n\004type\030\004 \002(\005\022 \n\tdzMessage\030\005 \001(\0132\r.mj.DZM" +
      "essageB\035\n\021protobuf.clazz.mjB\010KwxProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mj_KWXLiangCard_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mj_KWXLiangCard_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_KWXLiangCard_descriptor,
              new java.lang.String[] { "OperateCard", "OperateCode", "KouCards", "KouCount", });
          internal_static_mj_DZMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mj_DZMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_DZMessage_descriptor,
              new java.lang.String[] { "Card", "EndChuZi", });
          internal_static_mj_PlayerDZMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mj_PlayerDZMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_PlayerDZMessage_descriptor,
              new java.lang.String[] { "Status", "ViewCard", "CanCard", "Type", "DzMessage", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
