// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mj/zhuoji.proto

package protobuf.clazz.mj;

public final class ZhuoJiPro {
  private ZhuoJiPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SigonDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 描述ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 描述ID
     * </pre>
     */
    int getId();

    // optional int32 card_data = 2;
    /**
     * <code>optional int32 card_data = 2;</code>
     */
    boolean hasCardData();
    /**
     * <code>optional int32 card_data = 2;</code>
     */
    int getCardData();

    // required int32 score = 3;
    /**
     * <code>required int32 score = 3;</code>
     */
    boolean hasScore();
    /**
     * <code>required int32 score = 3;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code mj.SigonDetail}
   */
  public static final class SigonDetail extends
      com.google.protobuf.GeneratedMessage
      implements SigonDetailOrBuilder {
    // Use SigonDetail.newBuilder() to construct.
    private SigonDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SigonDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SigonDetail defaultInstance;
    public static SigonDetail getDefaultInstance() {
      return defaultInstance;
    }

    public SigonDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SigonDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cardData_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_SigonDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_SigonDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.ZhuoJiPro.SigonDetail.class, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<SigonDetail> PARSER =
        new com.google.protobuf.AbstractParser<SigonDetail>() {
      public SigonDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SigonDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SigonDetail> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 描述ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     *
     * <pre>
     * 描述ID
     * </pre>
     */
    public int getId() {
      return id_;
    }

    // optional int32 card_data = 2;
    public static final int CARD_DATA_FIELD_NUMBER = 2;
    private int cardData_;
    /**
     * <code>optional int32 card_data = 2;</code>
     */
    public boolean hasCardData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 card_data = 2;</code>
     */
    public int getCardData() {
      return cardData_;
    }

    // required int32 score = 3;
    public static final int SCORE_FIELD_NUMBER = 3;
    private int score_;
    /**
     * <code>required int32 score = 3;</code>
     */
    public boolean hasScore() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 score = 3;</code>
     */
    public int getScore() {
      return score_;
    }

    private void initFields() {
      id_ = 0;
      cardData_ = 0;
      score_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasScore()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cardData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, score_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cardData_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, score_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.SigonDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.ZhuoJiPro.SigonDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.SigonDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_SigonDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_SigonDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.ZhuoJiPro.SigonDetail.class, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder.class);
      }

      // Construct using protobuf.clazz.mj.ZhuoJiPro.SigonDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cardData_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        score_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_SigonDetail_descriptor;
      }

      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail getDefaultInstanceForType() {
        return protobuf.clazz.mj.ZhuoJiPro.SigonDetail.getDefaultInstance();
      }

      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail build() {
        protobuf.clazz.mj.ZhuoJiPro.SigonDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail buildPartial() {
        protobuf.clazz.mj.ZhuoJiPro.SigonDetail result = new protobuf.clazz.mj.ZhuoJiPro.SigonDetail(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cardData_ = cardData_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.score_ = score_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.ZhuoJiPro.SigonDetail) {
          return mergeFrom((protobuf.clazz.mj.ZhuoJiPro.SigonDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.ZhuoJiPro.SigonDetail other) {
        if (other == protobuf.clazz.mj.ZhuoJiPro.SigonDetail.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCardData()) {
          setCardData(other.getCardData());
        }
        if (other.hasScore()) {
          setScore(other.getScore());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasScore()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.ZhuoJiPro.SigonDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.ZhuoJiPro.SigonDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 描述ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 描述ID
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 描述ID
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       *
       * <pre>
       * 描述ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 card_data = 2;
      private int cardData_ ;
      /**
       * <code>optional int32 card_data = 2;</code>
       */
      public boolean hasCardData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 card_data = 2;</code>
       */
      public int getCardData() {
        return cardData_;
      }
      /**
       * <code>optional int32 card_data = 2;</code>
       */
      public Builder setCardData(int value) {
        bitField0_ |= 0x00000002;
        cardData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 card_data = 2;</code>
       */
      public Builder clearCardData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cardData_ = 0;
        onChanged();
        return this;
      }

      // required int32 score = 3;
      private int score_ ;
      /**
       * <code>required int32 score = 3;</code>
       */
      public boolean hasScore() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 score = 3;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>required int32 score = 3;</code>
       */
      public Builder setScore(int value) {
        bitField0_ |= 0x00000004;
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 score = 3;</code>
       */
      public Builder clearScore() {
        bitField0_ = (bitField0_ & ~0x00000004);
        score_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mj.SigonDetail)
    }

    static {
      defaultInstance = new SigonDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.SigonDetail)
  }

  public interface PersonDetailOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .mj.SigonDetail detail = 1;
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail> 
        getDetailList();
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    protobuf.clazz.mj.ZhuoJiPro.SigonDetail getDetail(int index);
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    int getDetailCount();
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder> 
        getDetailOrBuilderList();
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder getDetailOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mj.PersonDetail}
   */
  public static final class PersonDetail extends
      com.google.protobuf.GeneratedMessage
      implements PersonDetailOrBuilder {
    // Use PersonDetail.newBuilder() to construct.
    private PersonDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PersonDetail(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PersonDetail defaultInstance;
    public static PersonDetail getDefaultInstance() {
      return defaultInstance;
    }

    public PersonDetail getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PersonDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                detail_ = new java.util.ArrayList<protobuf.clazz.mj.ZhuoJiPro.SigonDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              detail_.add(input.readMessage(protobuf.clazz.mj.ZhuoJiPro.SigonDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          detail_ = java.util.Collections.unmodifiableList(detail_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_PersonDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_PersonDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.ZhuoJiPro.PersonDetail.class, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder.class);
    }

    public static com.google.protobuf.Parser<PersonDetail> PARSER =
        new com.google.protobuf.AbstractParser<PersonDetail>() {
      public PersonDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonDetail(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PersonDetail> getParserForType() {
      return PARSER;
    }

    // repeated .mj.SigonDetail detail = 1;
    public static final int DETAIL_FIELD_NUMBER = 1;
    private java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail> detail_;
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    public java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail> getDetailList() {
      return detail_;
    }
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    public java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder> 
        getDetailOrBuilderList() {
      return detail_;
    }
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    public int getDetailCount() {
      return detail_.size();
    }
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    public protobuf.clazz.mj.ZhuoJiPro.SigonDetail getDetail(int index) {
      return detail_.get(index);
    }
    /**
     * <code>repeated .mj.SigonDetail detail = 1;</code>
     */
    public protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder getDetailOrBuilder(
        int index) {
      return detail_.get(index);
    }

    private void initFields() {
      detail_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getDetailCount(); i++) {
        if (!getDetail(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < detail_.size(); i++) {
        output.writeMessage(1, detail_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < detail_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, detail_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.PersonDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.ZhuoJiPro.PersonDetail prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.PersonDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_PersonDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_PersonDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.ZhuoJiPro.PersonDetail.class, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder.class);
      }

      // Construct using protobuf.clazz.mj.ZhuoJiPro.PersonDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDetailFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (detailBuilder_ == null) {
          detail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          detailBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_PersonDetail_descriptor;
      }

      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail getDefaultInstanceForType() {
        return protobuf.clazz.mj.ZhuoJiPro.PersonDetail.getDefaultInstance();
      }

      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail build() {
        protobuf.clazz.mj.ZhuoJiPro.PersonDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail buildPartial() {
        protobuf.clazz.mj.ZhuoJiPro.PersonDetail result = new protobuf.clazz.mj.ZhuoJiPro.PersonDetail(this);
        int from_bitField0_ = bitField0_;
        if (detailBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            detail_ = java.util.Collections.unmodifiableList(detail_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.detail_ = detail_;
        } else {
          result.detail_ = detailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.ZhuoJiPro.PersonDetail) {
          return mergeFrom((protobuf.clazz.mj.ZhuoJiPro.PersonDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.ZhuoJiPro.PersonDetail other) {
        if (other == protobuf.clazz.mj.ZhuoJiPro.PersonDetail.getDefaultInstance()) return this;
        if (detailBuilder_ == null) {
          if (!other.detail_.isEmpty()) {
            if (detail_.isEmpty()) {
              detail_ = other.detail_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDetailIsMutable();
              detail_.addAll(other.detail_);
            }
            onChanged();
          }
        } else {
          if (!other.detail_.isEmpty()) {
            if (detailBuilder_.isEmpty()) {
              detailBuilder_.dispose();
              detailBuilder_ = null;
              detail_ = other.detail_;
              bitField0_ = (bitField0_ & ~0x00000001);
              detailBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDetailFieldBuilder() : null;
            } else {
              detailBuilder_.addAllMessages(other.detail_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDetailCount(); i++) {
          if (!getDetail(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.ZhuoJiPro.PersonDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.ZhuoJiPro.PersonDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .mj.SigonDetail detail = 1;
      private java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail> detail_ =
        java.util.Collections.emptyList();
      private void ensureDetailIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          detail_ = new java.util.ArrayList<protobuf.clazz.mj.ZhuoJiPro.SigonDetail>(detail_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.ZhuoJiPro.SigonDetail, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder> detailBuilder_;

      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail> getDetailList() {
        if (detailBuilder_ == null) {
          return java.util.Collections.unmodifiableList(detail_);
        } else {
          return detailBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public int getDetailCount() {
        if (detailBuilder_ == null) {
          return detail_.size();
        } else {
          return detailBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail getDetail(int index) {
        if (detailBuilder_ == null) {
          return detail_.get(index);
        } else {
          return detailBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder setDetail(
          int index, protobuf.clazz.mj.ZhuoJiPro.SigonDetail value) {
        if (detailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailIsMutable();
          detail_.set(index, value);
          onChanged();
        } else {
          detailBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder setDetail(
          int index, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder builderForValue) {
        if (detailBuilder_ == null) {
          ensureDetailIsMutable();
          detail_.set(index, builderForValue.build());
          onChanged();
        } else {
          detailBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder addDetail(protobuf.clazz.mj.ZhuoJiPro.SigonDetail value) {
        if (detailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailIsMutable();
          detail_.add(value);
          onChanged();
        } else {
          detailBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder addDetail(
          int index, protobuf.clazz.mj.ZhuoJiPro.SigonDetail value) {
        if (detailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetailIsMutable();
          detail_.add(index, value);
          onChanged();
        } else {
          detailBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder addDetail(
          protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder builderForValue) {
        if (detailBuilder_ == null) {
          ensureDetailIsMutable();
          detail_.add(builderForValue.build());
          onChanged();
        } else {
          detailBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder addDetail(
          int index, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder builderForValue) {
        if (detailBuilder_ == null) {
          ensureDetailIsMutable();
          detail_.add(index, builderForValue.build());
          onChanged();
        } else {
          detailBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder addAllDetail(
          java.lang.Iterable<? extends protobuf.clazz.mj.ZhuoJiPro.SigonDetail> values) {
        if (detailBuilder_ == null) {
          ensureDetailIsMutable();
          super.addAll(values, detail_);
          onChanged();
        } else {
          detailBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder clearDetail() {
        if (detailBuilder_ == null) {
          detail_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          detailBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public Builder removeDetail(int index) {
        if (detailBuilder_ == null) {
          ensureDetailIsMutable();
          detail_.remove(index);
          onChanged();
        } else {
          detailBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder getDetailBuilder(
          int index) {
        return getDetailFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder getDetailOrBuilder(
          int index) {
        if (detailBuilder_ == null) {
          return detail_.get(index);  } else {
          return detailBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder> 
           getDetailOrBuilderList() {
        if (detailBuilder_ != null) {
          return detailBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(detail_);
        }
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder addDetailBuilder() {
        return getDetailFieldBuilder().addBuilder(
            protobuf.clazz.mj.ZhuoJiPro.SigonDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder addDetailBuilder(
          int index) {
        return getDetailFieldBuilder().addBuilder(
            index, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.SigonDetail detail = 1;</code>
       */
      public java.util.List<protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder> 
           getDetailBuilderList() {
        return getDetailFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.ZhuoJiPro.SigonDetail, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder> 
          getDetailFieldBuilder() {
        if (detailBuilder_ == null) {
          detailBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.clazz.mj.ZhuoJiPro.SigonDetail, protobuf.clazz.mj.ZhuoJiPro.SigonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.SigonDetailOrBuilder>(
                  detail_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          detail_ = null;
        }
        return detailBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mj.PersonDetail)
    }

    static {
      defaultInstance = new PersonDetail(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.PersonDetail)
  }

  public interface ResponseMagicOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .mj.PersonDetail person = 1;
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail> 
        getPersonList();
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    protobuf.clazz.mj.ZhuoJiPro.PersonDetail getPerson(int index);
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    int getPersonCount();
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder> 
        getPersonOrBuilderList();
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder getPersonOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code mj.ResponseMagic}
   */
  public static final class ResponseMagic extends
      com.google.protobuf.GeneratedMessage
      implements ResponseMagicOrBuilder {
    // Use ResponseMagic.newBuilder() to construct.
    private ResponseMagic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ResponseMagic(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ResponseMagic defaultInstance;
    public static ResponseMagic getDefaultInstance() {
      return defaultInstance;
    }

    public ResponseMagic getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMagic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                person_ = new java.util.ArrayList<protobuf.clazz.mj.ZhuoJiPro.PersonDetail>();
                mutable_bitField0_ |= 0x00000001;
              }
              person_.add(input.readMessage(protobuf.clazz.mj.ZhuoJiPro.PersonDetail.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = java.util.Collections.unmodifiableList(person_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_ResponseMagic_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_ResponseMagic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.class, protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.Builder.class);
    }

    public static com.google.protobuf.Parser<ResponseMagic> PARSER =
        new com.google.protobuf.AbstractParser<ResponseMagic>() {
      public ResponseMagic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMagic(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMagic> getParserForType() {
      return PARSER;
    }

    // repeated .mj.PersonDetail person = 1;
    public static final int PERSON_FIELD_NUMBER = 1;
    private java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail> person_;
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    public java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail> getPersonList() {
      return person_;
    }
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    public java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    public int getPersonCount() {
      return person_.size();
    }
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    public protobuf.clazz.mj.ZhuoJiPro.PersonDetail getPerson(int index) {
      return person_.get(index);
    }
    /**
     * <code>repeated .mj.PersonDetail person = 1;</code>
     */
    public protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }

    private void initFields() {
      person_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(1, person_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, person_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.mj.ZhuoJiPro.ResponseMagic prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mj.ResponseMagic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.mj.ZhuoJiPro.ResponseMagicOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_ResponseMagic_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_ResponseMagic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.class, protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.Builder.class);
      }

      // Construct using protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          personBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.mj.ZhuoJiPro.internal_static_mj_ResponseMagic_descriptor;
      }

      public protobuf.clazz.mj.ZhuoJiPro.ResponseMagic getDefaultInstanceForType() {
        return protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.getDefaultInstance();
      }

      public protobuf.clazz.mj.ZhuoJiPro.ResponseMagic build() {
        protobuf.clazz.mj.ZhuoJiPro.ResponseMagic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.mj.ZhuoJiPro.ResponseMagic buildPartial() {
        protobuf.clazz.mj.ZhuoJiPro.ResponseMagic result = new protobuf.clazz.mj.ZhuoJiPro.ResponseMagic(this);
        int from_bitField0_ = bitField0_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.mj.ZhuoJiPro.ResponseMagic) {
          return mergeFrom((protobuf.clazz.mj.ZhuoJiPro.ResponseMagic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.mj.ZhuoJiPro.ResponseMagic other) {
        if (other == protobuf.clazz.mj.ZhuoJiPro.ResponseMagic.getDefaultInstance()) return this;
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000001);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.mj.ZhuoJiPro.ResponseMagic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.mj.ZhuoJiPro.ResponseMagic) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .mj.PersonDetail person = 1;
      private java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          person_ = new java.util.ArrayList<protobuf.clazz.mj.ZhuoJiPro.PersonDetail>(person_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.ZhuoJiPro.PersonDetail, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder> personBuilder_;

      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder setPerson(
          int index, protobuf.clazz.mj.ZhuoJiPro.PersonDetail value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder setPerson(
          int index, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder addPerson(protobuf.clazz.mj.ZhuoJiPro.PersonDetail value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder addPerson(
          int index, protobuf.clazz.mj.ZhuoJiPro.PersonDetail value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder addPerson(
          protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder addPerson(
          int index, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder addAllPerson(
          java.lang.Iterable<? extends protobuf.clazz.mj.ZhuoJiPro.PersonDetail> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public java.util.List<? extends protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            protobuf.clazz.mj.ZhuoJiPro.PersonDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.getDefaultInstance());
      }
      /**
       * <code>repeated .mj.PersonDetail person = 1;</code>
       */
      public java.util.List<protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          protobuf.clazz.mj.ZhuoJiPro.PersonDetail, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              protobuf.clazz.mj.ZhuoJiPro.PersonDetail, protobuf.clazz.mj.ZhuoJiPro.PersonDetail.Builder, protobuf.clazz.mj.ZhuoJiPro.PersonDetailOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:mj.ResponseMagic)
    }

    static {
      defaultInstance = new ResponseMagic(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mj.ResponseMagic)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_SigonDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_SigonDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_PersonDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_PersonDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mj_ResponseMagic_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mj_ResponseMagic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mj/zhuoji.proto\022\002mj\032\024basic/protocol.pr" +
      "oto\";\n\013SigonDetail\022\n\n\002id\030\001 \002(\005\022\021\n\tcard_d" +
      "ata\030\002 \001(\005\022\r\n\005score\030\003 \002(\005\"/\n\014PersonDetail" +
      "\022\037\n\006detail\030\001 \003(\0132\017.mj.SigonDetail\"1\n\rRes" +
      "ponseMagic\022 \n\006person\030\001 \003(\0132\020.mj.PersonDe" +
      "tailB\036\n\021protobuf.clazz.mjB\tZhuoJiPro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mj_SigonDetail_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mj_SigonDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_SigonDetail_descriptor,
              new java.lang.String[] { "Id", "CardData", "Score", });
          internal_static_mj_PersonDetail_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_mj_PersonDetail_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_PersonDetail_descriptor,
              new java.lang.String[] { "Detail", });
          internal_static_mj_ResponseMagic_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_mj_ResponseMagic_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mj_ResponseMagic_descriptor,
              new java.lang.String[] { "Person", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
