// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activity/activityNewYearServer.proto

package protobuf.clazz.activity;

public final class ActivityNewYearServerProto {
  private ActivityNewYearServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewYearPlayerDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int64 accountId = 1;
    /**
     * <code>optional int64 accountId = 1;</code>
     *
     * <pre>
     *	optional int64 lastRereshTime
     * </pre>
     */
    boolean hasAccountId();
    /**
     * <code>optional int64 accountId = 1;</code>
     *
     * <pre>
     *	optional int64 lastRereshTime
     * </pre>
     */
    long getAccountId();
  }
  /**
   * Protobuf type {@code redpacket.NewYearPlayerData}
   */
  public static final class NewYearPlayerData extends
      com.google.protobuf.GeneratedMessage
      implements NewYearPlayerDataOrBuilder {
    // Use NewYearPlayerData.newBuilder() to construct.
    private NewYearPlayerData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NewYearPlayerData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NewYearPlayerData defaultInstance;
    public static NewYearPlayerData getDefaultInstance() {
      return defaultInstance;
    }

    public NewYearPlayerData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NewYearPlayerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              accountId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.activity.ActivityNewYearServerProto.internal_static_redpacket_NewYearPlayerData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.activity.ActivityNewYearServerProto.internal_static_redpacket_NewYearPlayerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.class, protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.Builder.class);
    }

    public static com.google.protobuf.Parser<NewYearPlayerData> PARSER =
        new com.google.protobuf.AbstractParser<NewYearPlayerData>() {
      public NewYearPlayerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewYearPlayerData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewYearPlayerData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int64 accountId = 1;
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    private long accountId_;
    /**
     * <code>optional int64 accountId = 1;</code>
     *
     * <pre>
     *	optional int64 lastRereshTime
     * </pre>
     */
    public boolean hasAccountId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 accountId = 1;</code>
     *
     * <pre>
     *	optional int64 lastRereshTime
     * </pre>
     */
    public long getAccountId() {
      return accountId_;
    }

    private void initFields() {
      accountId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, accountId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, accountId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code redpacket.NewYearPlayerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.activity.ActivityNewYearServerProto.internal_static_redpacket_NewYearPlayerData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.activity.ActivityNewYearServerProto.internal_static_redpacket_NewYearPlayerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.class, protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.Builder.class);
      }

      // Construct using protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accountId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.activity.ActivityNewYearServerProto.internal_static_redpacket_NewYearPlayerData_descriptor;
      }

      public protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData getDefaultInstanceForType() {
        return protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.getDefaultInstance();
      }

      public protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData build() {
        protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData buildPartial() {
        protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData result = new protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accountId_ = accountId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData) {
          return mergeFrom((protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData other) {
        if (other == protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData.getDefaultInstance()) return this;
        if (other.hasAccountId()) {
          setAccountId(other.getAccountId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.activity.ActivityNewYearServerProto.NewYearPlayerData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int64 accountId = 1;
      private long accountId_ ;
      /**
       * <code>optional int64 accountId = 1;</code>
       *
       * <pre>
       *	optional int64 lastRereshTime
       * </pre>
       */
      public boolean hasAccountId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 accountId = 1;</code>
       *
       * <pre>
       *	optional int64 lastRereshTime
       * </pre>
       */
      public long getAccountId() {
        return accountId_;
      }
      /**
       * <code>optional int64 accountId = 1;</code>
       *
       * <pre>
       *	optional int64 lastRereshTime
       * </pre>
       */
      public Builder setAccountId(long value) {
        bitField0_ |= 0x00000001;
        accountId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 accountId = 1;</code>
       *
       * <pre>
       *	optional int64 lastRereshTime
       * </pre>
       */
      public Builder clearAccountId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accountId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:redpacket.NewYearPlayerData)
    }

    static {
      defaultInstance = new NewYearPlayerData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:redpacket.NewYearPlayerData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_redpacket_NewYearPlayerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_redpacket_NewYearPlayerData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$activity/activityNewYearServer.proto\022\t" +
      "redpacket\"&\n\021NewYearPlayerData\022\021\n\taccoun" +
      "tId\030\001 \001(\003B5\n\027protobuf.clazz.activityB\032Ac" +
      "tivityNewYearServerProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_redpacket_NewYearPlayerData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_redpacket_NewYearPlayerData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_redpacket_NewYearPlayerData_descriptor,
              new java.lang.String[] { "AccountId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
