// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic/extendsProto.proto

package protobuf.clazz.extendCommon;

public final class ExtendsProto {
  private ExtendsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PermitLessRepOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 playerNumber = 1;
    /**
     * <code>optional int32 playerNumber = 1;</code>
     *
     * <pre>
     *允许少人模式的人数
     * </pre>
     */
    boolean hasPlayerNumber();
    /**
     * <code>optional int32 playerNumber = 1;</code>
     *
     * <pre>
     *允许少人模式的人数
     * </pre>
     */
    int getPlayerNumber();
  }
  /**
   * Protobuf type {@code extendCommon.PermitLessRep}
   *
   * <pre>
   *通用字节流扩展pb
   * </pre>
   */
  public static final class PermitLessRep extends
      com.google.protobuf.GeneratedMessage
      implements PermitLessRepOrBuilder {
    // Use PermitLessRep.newBuilder() to construct.
    private PermitLessRep(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PermitLessRep(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PermitLessRep defaultInstance;
    public static PermitLessRep getDefaultInstance() {
      return defaultInstance;
    }

    public PermitLessRep getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PermitLessRep(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              playerNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.extendCommon.ExtendsProto.internal_static_extendCommon_PermitLessRep_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.extendCommon.ExtendsProto.internal_static_extendCommon_PermitLessRep_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.class, protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.Builder.class);
    }

    public static com.google.protobuf.Parser<PermitLessRep> PARSER =
        new com.google.protobuf.AbstractParser<PermitLessRep>() {
      public PermitLessRep parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PermitLessRep(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PermitLessRep> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 playerNumber = 1;
    public static final int PLAYERNUMBER_FIELD_NUMBER = 1;
    private int playerNumber_;
    /**
     * <code>optional int32 playerNumber = 1;</code>
     *
     * <pre>
     *允许少人模式的人数
     * </pre>
     */
    public boolean hasPlayerNumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 playerNumber = 1;</code>
     *
     * <pre>
     *允许少人模式的人数
     * </pre>
     */
    public int getPlayerNumber() {
      return playerNumber_;
    }

    private void initFields() {
      playerNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, playerNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, playerNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code extendCommon.PermitLessRep}
     *
     * <pre>
     *通用字节流扩展pb
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.extendCommon.ExtendsProto.PermitLessRepOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.extendCommon.ExtendsProto.internal_static_extendCommon_PermitLessRep_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.extendCommon.ExtendsProto.internal_static_extendCommon_PermitLessRep_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.class, protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.Builder.class);
      }

      // Construct using protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        playerNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.extendCommon.ExtendsProto.internal_static_extendCommon_PermitLessRep_descriptor;
      }

      public protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep getDefaultInstanceForType() {
        return protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.getDefaultInstance();
      }

      public protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep build() {
        protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep buildPartial() {
        protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep result = new protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.playerNumber_ = playerNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep) {
          return mergeFrom((protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep other) {
        if (other == protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep.getDefaultInstance()) return this;
        if (other.hasPlayerNumber()) {
          setPlayerNumber(other.getPlayerNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.extendCommon.ExtendsProto.PermitLessRep) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 playerNumber = 1;
      private int playerNumber_ ;
      /**
       * <code>optional int32 playerNumber = 1;</code>
       *
       * <pre>
       *允许少人模式的人数
       * </pre>
       */
      public boolean hasPlayerNumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 playerNumber = 1;</code>
       *
       * <pre>
       *允许少人模式的人数
       * </pre>
       */
      public int getPlayerNumber() {
        return playerNumber_;
      }
      /**
       * <code>optional int32 playerNumber = 1;</code>
       *
       * <pre>
       *允许少人模式的人数
       * </pre>
       */
      public Builder setPlayerNumber(int value) {
        bitField0_ |= 0x00000001;
        playerNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playerNumber = 1;</code>
       *
       * <pre>
       *允许少人模式的人数
       * </pre>
       */
      public Builder clearPlayerNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        playerNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:extendCommon.PermitLessRep)
    }

    static {
      defaultInstance = new PermitLessRep(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:extendCommon.PermitLessRep)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_extendCommon_PermitLessRep_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_extendCommon_PermitLessRep_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030basic/extendsProto.proto\022\014extendCommon" +
      "\032\024basic/protocol.proto\032\022basic/common.pro" +
      "to\"%\n\rPermitLessRep\022\024\n\014playerNumber\030\001 \001(" +
      "\005B+\n\033protobuf.clazz.extendCommonB\014Extend" +
      "sProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_extendCommon_PermitLessRep_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_extendCommon_PermitLessRep_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_extendCommon_PermitLessRep_descriptor,
              new java.lang.String[] { "PlayerNumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
          protobuf.clazz.Common.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
