// Generated by the DBTool.exe,  DO NOT EDIT!

package com.cai.common.domain;

import java.util.Objects;

/**
 * db:yx_public , table:coin_box_category date:2018-11-14 10:35:03
 */
public final class CoinBoxCategoryModel extends DBBaseModel {

	/**
	 * serial uid
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 子游戏id
	 */
	private int gameTypeIndex;

	/**
	 * 所需局数
	 */
	private int gameCount;

	/**
	 * 奖励百分比，从赢得金币数量百分比活得
	 */
	private int rewardRatio;

	/**
	 * 开宝箱所需奖分
	 */
	private int goldRewardScore;

	/**
	 * 金宝箱id列表
	 */
	private String goldBoxIds;

	/**
	 * 开宝箱所需奖分
	 */
	private int silverRewardScore;

	/**
	 * 银宝箱id列表
	 */
	private String silverBoxIds;

	/**
	 * 开宝箱所需奖分
	 */
	private int copperRewardScore;

	/**
	 * 铜宝箱id列表
	 */
	private String copperBoxIds;

	/**
	 * 规则描述
	 */
	private String ruleDesc;

	/**
	 * 最后一次操作者
	 */
	private String operator;

	/**
	 * 操作日期
	 */
	private java.util.Date operatorDate;

	/**
	 * 状态，1true0false
	 */
	private boolean status;

	/**
	 * 子游戏id
	 */
	public void setGameTypeIndex(int gameTypeIndex) {
		if(Objects.equals(this.gameTypeIndex,gameTypeIndex)) 
			return;
		this.gameTypeIndex = gameTypeIndex;
		setNeedDB(true);
	}

	/**
	 * 子游戏id
	 */
	public int getGameTypeIndex() {
		return this.gameTypeIndex;
	}

	/**
	 * 所需局数
	 */
	public void setGameCount(int gameCount) {
		if(Objects.equals(this.gameCount,gameCount)) 
			return;
		this.gameCount = gameCount;
		setNeedDB(true);
	}

	/**
	 * 所需局数
	 */
	public int getGameCount() {
		return this.gameCount;
	}

	/**
	 * 奖励百分比，从赢得金币数量百分比活得
	 */
	public void setRewardRatio(int rewardRatio) {
		if(Objects.equals(this.rewardRatio,rewardRatio)) 
			return;
		this.rewardRatio = rewardRatio;
		setNeedDB(true);
	}

	/**
	 * 奖励百分比，从赢得金币数量百分比活得
	 */
	public int getRewardRatio() {
		return this.rewardRatio;
	}

	/**
	 * 开宝箱所需奖分
	 */
	public void setGoldRewardScore(int goldRewardScore) {
		if(Objects.equals(this.goldRewardScore,goldRewardScore)) 
			return;
		this.goldRewardScore = goldRewardScore;
		setNeedDB(true);
	}

	/**
	 * 开宝箱所需奖分
	 */
	public int getGoldRewardScore() {
		return this.goldRewardScore;
	}

	/**
	 * 金宝箱id列表
	 */
	public void setGoldBoxIds(String goldBoxIds) {
		if(Objects.equals(this.goldBoxIds,goldBoxIds)) 
			return;
		this.goldBoxIds = goldBoxIds;
		setNeedDB(true);
	}

	/**
	 * 金宝箱id列表
	 */
	public String getGoldBoxIds() {
		return this.goldBoxIds;
	}

	/**
	 * 开宝箱所需奖分
	 */
	public void setSilverRewardScore(int silverRewardScore) {
		if(Objects.equals(this.silverRewardScore,silverRewardScore)) 
			return;
		this.silverRewardScore = silverRewardScore;
		setNeedDB(true);
	}

	/**
	 * 开宝箱所需奖分
	 */
	public int getSilverRewardScore() {
		return this.silverRewardScore;
	}

	/**
	 * 银宝箱id列表
	 */
	public void setSilverBoxIds(String silverBoxIds) {
		if(Objects.equals(this.silverBoxIds,silverBoxIds)) 
			return;
		this.silverBoxIds = silverBoxIds;
		setNeedDB(true);
	}

	/**
	 * 银宝箱id列表
	 */
	public String getSilverBoxIds() {
		return this.silverBoxIds;
	}

	/**
	 * 开宝箱所需奖分
	 */
	public void setCopperRewardScore(int copperRewardScore) {
		if(Objects.equals(this.copperRewardScore,copperRewardScore)) 
			return;
		this.copperRewardScore = copperRewardScore;
		setNeedDB(true);
	}

	/**
	 * 开宝箱所需奖分
	 */
	public int getCopperRewardScore() {
		return this.copperRewardScore;
	}

	/**
	 * 铜宝箱id列表
	 */
	public void setCopperBoxIds(String copperBoxIds) {
		if(Objects.equals(this.copperBoxIds,copperBoxIds)) 
			return;
		this.copperBoxIds = copperBoxIds;
		setNeedDB(true);
	}

	/**
	 * 铜宝箱id列表
	 */
	public String getCopperBoxIds() {
		return this.copperBoxIds;
	}

	/**
	 * 规则描述
	 */
	public void setRuleDesc(String ruleDesc) {
		if(Objects.equals(this.ruleDesc,ruleDesc)) 
			return;
		this.ruleDesc = ruleDesc;
		setNeedDB(true);
	}

	/**
	 * 规则描述
	 */
	public String getRuleDesc() {
		return this.ruleDesc;
	}

	/**
	 * 最后一次操作者
	 */
	public void setOperator(String operator) {
		if(Objects.equals(this.operator,operator)) 
			return;
		this.operator = operator;
		setNeedDB(true);
	}

	/**
	 * 最后一次操作者
	 */
	public String getOperator() {
		return this.operator;
	}

	/**
	 * 操作日期
	 */
	public void setOperatorDate(java.util.Date operatorDate) {
		if(Objects.equals(this.operatorDate,operatorDate)) 
			return;
		this.operatorDate = operatorDate;
		setNeedDB(true);
	}

	/**
	 * 操作日期
	 */
	public java.util.Date getOperatorDate() {
		return this.operatorDate;
	}

	/**
	 * 状态，1true0false
	 */
	public void setStatus(boolean status) {
		if(Objects.equals(this.status,status)) 
			return;
		this.status = status;
		setNeedDB(true);
	}

	/**
	 * 状态，1true0false
	 */
	public boolean getStatus() {
		return this.status;
	}

}