// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic/OssSts.proto

package protobuf.clazz.ossSts;

public final class OssStsRsp {
  private OssStsRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OssStsClientRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ossSts.OssStsClientRequest}
   */
  public static final class OssStsClientRequest extends
      com.google.protobuf.GeneratedMessage
      implements OssStsClientRequestOrBuilder {
    // Use OssStsClientRequest.newBuilder() to construct.
    private OssStsClientRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OssStsClientRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OssStsClientRequest defaultInstance;
    public static OssStsClientRequest getDefaultInstance() {
      return defaultInstance;
    }

    public OssStsClientRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OssStsClientRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.class, protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<OssStsClientRequest> PARSER =
        new com.google.protobuf.AbstractParser<OssStsClientRequest>() {
      public OssStsClientRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OssStsClientRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OssStsClientRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ossSts.OssStsClientRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.class, protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.Builder.class);
      }

      // Construct using protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientRequest_descriptor;
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest getDefaultInstanceForType() {
        return protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.getDefaultInstance();
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest build() {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest buildPartial() {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest result = new protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest) {
          return mergeFrom((protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest other) {
        if (other == protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.ossSts.OssStsRsp.OssStsClientRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ossSts.OssStsClientRequest)
    }

    static {
      defaultInstance = new OssStsClientRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ossSts.OssStsClientRequest)
  }

  public interface OssStsClientResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string accessKeyId = 1;
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    boolean hasAccessKeyId();
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    java.lang.String getAccessKeyId();
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccessKeyIdBytes();

    // optional string accesKeySecret = 2;
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    boolean hasAccesKeySecret();
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    java.lang.String getAccesKeySecret();
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    com.google.protobuf.ByteString
        getAccesKeySecretBytes();

    // optional string securityToken = 3;
    /**
     * <code>optional string securityToken = 3;</code>
     */
    boolean hasSecurityToken();
    /**
     * <code>optional string securityToken = 3;</code>
     */
    java.lang.String getSecurityToken();
    /**
     * <code>optional string securityToken = 3;</code>
     */
    com.google.protobuf.ByteString
        getSecurityTokenBytes();
  }
  /**
   * Protobuf type {@code ossSts.OssStsClientResponse}
   */
  public static final class OssStsClientResponse extends
      com.google.protobuf.GeneratedMessage
      implements OssStsClientResponseOrBuilder {
    // Use OssStsClientResponse.newBuilder() to construct.
    private OssStsClientResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OssStsClientResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OssStsClientResponse defaultInstance;
    public static OssStsClientResponse getDefaultInstance() {
      return defaultInstance;
    }

    public OssStsClientResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OssStsClientResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              accessKeyId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              accesKeySecret_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              securityToken_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.class, protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<OssStsClientResponse> PARSER =
        new com.google.protobuf.AbstractParser<OssStsClientResponse>() {
      public OssStsClientResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OssStsClientResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OssStsClientResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string accessKeyId = 1;
    public static final int ACCESSKEYID_FIELD_NUMBER = 1;
    private java.lang.Object accessKeyId_;
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    public boolean hasAccessKeyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    public java.lang.String getAccessKeyId() {
      java.lang.Object ref = accessKeyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessKeyId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accessKeyId = 1;</code>
     *
     * <pre>
     *临时认证id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccessKeyIdBytes() {
      java.lang.Object ref = accessKeyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string accesKeySecret = 2;
    public static final int ACCESKEYSECRET_FIELD_NUMBER = 2;
    private java.lang.Object accesKeySecret_;
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    public boolean hasAccesKeySecret() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    public java.lang.String getAccesKeySecret() {
      java.lang.Object ref = accesKeySecret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accesKeySecret_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string accesKeySecret = 2;</code>
     *
     * <pre>
     *临时密钥
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAccesKeySecretBytes() {
      java.lang.Object ref = accesKeySecret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accesKeySecret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string securityToken = 3;
    public static final int SECURITYTOKEN_FIELD_NUMBER = 3;
    private java.lang.Object securityToken_;
    /**
     * <code>optional string securityToken = 3;</code>
     */
    public boolean hasSecurityToken() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string securityToken = 3;</code>
     */
    public java.lang.String getSecurityToken() {
      java.lang.Object ref = securityToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          securityToken_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string securityToken = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSecurityTokenBytes() {
      java.lang.Object ref = securityToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        securityToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      accessKeyId_ = "";
      accesKeySecret_ = "";
      securityToken_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAccessKeyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAccesKeySecretBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSecurityTokenBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAccessKeyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAccesKeySecretBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSecurityTokenBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ossSts.OssStsClientResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.class, protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.Builder.class);
      }

      // Construct using protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        accessKeyId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        accesKeySecret_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        securityToken_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.ossSts.OssStsRsp.internal_static_ossSts_OssStsClientResponse_descriptor;
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse getDefaultInstanceForType() {
        return protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.getDefaultInstance();
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse build() {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse buildPartial() {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse result = new protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.accessKeyId_ = accessKeyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accesKeySecret_ = accesKeySecret_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.securityToken_ = securityToken_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse) {
          return mergeFrom((protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse other) {
        if (other == protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse.getDefaultInstance()) return this;
        if (other.hasAccessKeyId()) {
          bitField0_ |= 0x00000001;
          accessKeyId_ = other.accessKeyId_;
          onChanged();
        }
        if (other.hasAccesKeySecret()) {
          bitField0_ |= 0x00000002;
          accesKeySecret_ = other.accesKeySecret_;
          onChanged();
        }
        if (other.hasSecurityToken()) {
          bitField0_ |= 0x00000004;
          securityToken_ = other.securityToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.ossSts.OssStsRsp.OssStsClientResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string accessKeyId = 1;
      private java.lang.Object accessKeyId_ = "";
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public boolean hasAccessKeyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public java.lang.String getAccessKeyId() {
        java.lang.Object ref = accessKeyId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accessKeyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccessKeyIdBytes() {
        java.lang.Object ref = accessKeyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessKeyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public Builder setAccessKeyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accessKeyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public Builder clearAccessKeyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        accessKeyId_ = getDefaultInstance().getAccessKeyId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessKeyId = 1;</code>
       *
       * <pre>
       *临时认证id
       * </pre>
       */
      public Builder setAccessKeyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        accessKeyId_ = value;
        onChanged();
        return this;
      }

      // optional string accesKeySecret = 2;
      private java.lang.Object accesKeySecret_ = "";
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public boolean hasAccesKeySecret() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public java.lang.String getAccesKeySecret() {
        java.lang.Object ref = accesKeySecret_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          accesKeySecret_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAccesKeySecretBytes() {
        java.lang.Object ref = accesKeySecret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accesKeySecret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public Builder setAccesKeySecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accesKeySecret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public Builder clearAccesKeySecret() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accesKeySecret_ = getDefaultInstance().getAccesKeySecret();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accesKeySecret = 2;</code>
       *
       * <pre>
       *临时密钥
       * </pre>
       */
      public Builder setAccesKeySecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        accesKeySecret_ = value;
        onChanged();
        return this;
      }

      // optional string securityToken = 3;
      private java.lang.Object securityToken_ = "";
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public boolean hasSecurityToken() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public java.lang.String getSecurityToken() {
        java.lang.Object ref = securityToken_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          securityToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSecurityTokenBytes() {
        java.lang.Object ref = securityToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          securityToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public Builder setSecurityToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        securityToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public Builder clearSecurityToken() {
        bitField0_ = (bitField0_ & ~0x00000004);
        securityToken_ = getDefaultInstance().getSecurityToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string securityToken = 3;</code>
       */
      public Builder setSecurityTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        securityToken_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ossSts.OssStsClientResponse)
    }

    static {
      defaultInstance = new OssStsClientResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ossSts.OssStsClientResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ossSts_OssStsClientRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ossSts_OssStsClientRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ossSts_OssStsClientResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ossSts_OssStsClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022basic/OssSts.proto\022\006ossSts\"\025\n\023OssStsCl" +
      "ientRequest\"Z\n\024OssStsClientResponse\022\023\n\013a" +
      "ccessKeyId\030\001 \001(\t\022\026\n\016accesKeySecret\030\002 \001(\t" +
      "\022\025\n\rsecurityToken\030\003 \001(\tB\"\n\025protobuf.claz" +
      "z.ossStsB\tOssStsRsp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ossSts_OssStsClientRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ossSts_OssStsClientRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ossSts_OssStsClientRequest_descriptor,
              new java.lang.String[] { });
          internal_static_ossSts_OssStsClientResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ossSts_OssStsClientResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ossSts_OssStsClientResponse_descriptor,
              new java.lang.String[] { "AccessKeyId", "AccesKeySecret", "SecurityToken", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
