// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: laopai/xplp.proto

package protobuf.clazz.laopai;

public final class LpRsp {
  private LpRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LP_XU_JIPAIQIOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 out_card_index = 1;
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    java.util.List<java.lang.Integer> getOutCardIndexList();
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    int getOutCardIndexCount();
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    int getOutCardIndex(int index);
  }
  /**
   * Protobuf type {@code laopai.LP_XU_JIPAIQI}
   */
  public static final class LP_XU_JIPAIQI extends
      com.google.protobuf.GeneratedMessage
      implements LP_XU_JIPAIQIOrBuilder {
    // Use LP_XU_JIPAIQI.newBuilder() to construct.
    private LP_XU_JIPAIQI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LP_XU_JIPAIQI(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LP_XU_JIPAIQI defaultInstance;
    public static LP_XU_JIPAIQI getDefaultInstance() {
      return defaultInstance;
    }

    public LP_XU_JIPAIQI getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LP_XU_JIPAIQI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                outCardIndex_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              outCardIndex_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                outCardIndex_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                outCardIndex_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          outCardIndex_ = java.util.Collections.unmodifiableList(outCardIndex_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.clazz.laopai.LpRsp.internal_static_laopai_LP_XU_JIPAIQI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.clazz.laopai.LpRsp.internal_static_laopai_LP_XU_JIPAIQI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.class, protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.Builder.class);
    }

    public static com.google.protobuf.Parser<LP_XU_JIPAIQI> PARSER =
        new com.google.protobuf.AbstractParser<LP_XU_JIPAIQI>() {
      public LP_XU_JIPAIQI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LP_XU_JIPAIQI(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LP_XU_JIPAIQI> getParserForType() {
      return PARSER;
    }

    // repeated int32 out_card_index = 1;
    public static final int OUT_CARD_INDEX_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> outCardIndex_;
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getOutCardIndexList() {
      return outCardIndex_;
    }
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    public int getOutCardIndexCount() {
      return outCardIndex_.size();
    }
    /**
     * <code>repeated int32 out_card_index = 1;</code>
     *
     * <pre>
     *出牌索引
     * </pre>
     */
    public int getOutCardIndex(int index) {
      return outCardIndex_.get(index);
    }

    private void initFields() {
      outCardIndex_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < outCardIndex_.size(); i++) {
        output.writeInt32(1, outCardIndex_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < outCardIndex_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(outCardIndex_.get(i));
        }
        size += dataSize;
        size += 1 * getOutCardIndexList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code laopai.LP_XU_JIPAIQI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.clazz.laopai.LpRsp.internal_static_laopai_LP_XU_JIPAIQI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.clazz.laopai.LpRsp.internal_static_laopai_LP_XU_JIPAIQI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.class, protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.Builder.class);
      }

      // Construct using protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        outCardIndex_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.clazz.laopai.LpRsp.internal_static_laopai_LP_XU_JIPAIQI_descriptor;
      }

      public protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI getDefaultInstanceForType() {
        return protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.getDefaultInstance();
      }

      public protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI build() {
        protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI buildPartial() {
        protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI result = new protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          outCardIndex_ = java.util.Collections.unmodifiableList(outCardIndex_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.outCardIndex_ = outCardIndex_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI) {
          return mergeFrom((protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI other) {
        if (other == protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI.getDefaultInstance()) return this;
        if (!other.outCardIndex_.isEmpty()) {
          if (outCardIndex_.isEmpty()) {
            outCardIndex_ = other.outCardIndex_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOutCardIndexIsMutable();
            outCardIndex_.addAll(other.outCardIndex_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.clazz.laopai.LpRsp.LP_XU_JIPAIQI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 out_card_index = 1;
      private java.util.List<java.lang.Integer> outCardIndex_ = java.util.Collections.emptyList();
      private void ensureOutCardIndexIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          outCardIndex_ = new java.util.ArrayList<java.lang.Integer>(outCardIndex_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getOutCardIndexList() {
        return java.util.Collections.unmodifiableList(outCardIndex_);
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public int getOutCardIndexCount() {
        return outCardIndex_.size();
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public int getOutCardIndex(int index) {
        return outCardIndex_.get(index);
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public Builder setOutCardIndex(
          int index, int value) {
        ensureOutCardIndexIsMutable();
        outCardIndex_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public Builder addOutCardIndex(int value) {
        ensureOutCardIndexIsMutable();
        outCardIndex_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public Builder addAllOutCardIndex(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureOutCardIndexIsMutable();
        super.addAll(values, outCardIndex_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 out_card_index = 1;</code>
       *
       * <pre>
       *出牌索引
       * </pre>
       */
      public Builder clearOutCardIndex() {
        outCardIndex_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:laopai.LP_XU_JIPAIQI)
    }

    static {
      defaultInstance = new LP_XU_JIPAIQI(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:laopai.LP_XU_JIPAIQI)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_laopai_LP_XU_JIPAIQI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_laopai_LP_XU_JIPAIQI_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021laopai/xplp.proto\022\006laopai\032\024basic/proto" +
      "col.proto\"\'\n\rLP_XU_JIPAIQI\022\026\n\016out_card_i" +
      "ndex\030\001 \003(\005B\036\n\025protobuf.clazz.laopaiB\005LpR" +
      "sp"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_laopai_LP_XU_JIPAIQI_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_laopai_LP_XU_JIPAIQI_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_laopai_LP_XU_JIPAIQI_descriptor,
              new java.lang.String[] { "OutCardIndex", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.clazz.Protocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
